[{
  "dealerOrder": "",
  "cityOrder": "",
  "dealerCategory": "",
  "addressLine1": "811 Elizabeth St",
  "addressLine2": "",
  "articleId": "",
  "award": "",
  "city": "Zetland",
  "country": "",
  "dealerCode": "28010",
  "dealerInfo": "28010#@##@#City Ford",
  "dealershipName": "City Ford",
  "email": "reception@cityford.com.au",
  "fax": "02-9332 8195",
  "pma": "N/A",
  "localDealerCode": "",
  "name": "",
  "pageId": "",
  "phoneNumber1": "02-9331 5000",
  "phoneNumber2": "",
  "postcode": "2017",
  "state": "NSW",
  "website": "www.cityford.com.au",
  "abn": "84-088-817-912",
  "authorised": "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
  "function": "Main Site",
  "salesDealerFlag": "Y",
  "fullXtimeParticipant": "N",
  "consumerURL": "",
  "mobileURL": ""
},{
  "dealerOrder": "",
  "cityOrder": "",
  "dealerCategory": "",
  "addressLine1": "204 Hume Highway",
  "addressLine2": "",
  "articleId": "",
  "award": "",
  "city": "Chullora",
  "country": "",
  "dealerCode": "28012",
  "dealerInfo": "28012#@##@#City Ford",
  "dealershipName": "City Ford",
  "email": "reception@cityford.com.au",
  "fax": "02-9742 5070",
  "pma": "N/A",
  "localDealerCode": "",
  "name": "",
  "pageId": "",
  "phoneNumber1": "02-9642 0385",
  "phoneNumber2": "",
  "postcode": "2190",
  "state": "NSW",
  "website": "www.cityford.com.au",
  "abn": "84-088-817-912",
  "authorised": "CPS Participating, Used Cars",
  "function": "Used Vehicles Only",
  "salesDealerFlag": "",
  "fullXtimeParticipant": "Y",
  "consumerURL": "",
  "mobileURL": ""
},{
  "dealerOrder": "",
  "cityOrder": "",
  "dealerCategory": "",
  "addressLine1": "734 Elizabeth Street",
  "addressLine2": "",
  "articleId": "",
  "award": "",
  "city": "Melbourne",
  "country": "",
  "dealerCode": "36220",
  "dealerInfo": "36220#@##@#City Ford",
  "dealershipName": "City Ford",
  "email": "info@city-ford.com.au",
  "fax": "03-9347 4635",
  "pma": "N/A",
  "localDealerCode": "",
  "name": "",
  "pageId": "",
  "phoneNumber1": "03-9349 1277",
  "phoneNumber2": "",
  "postcode": "3000",
  "state": "VIC",
  "website": "www.city-ford.com.au",
  "abn": "82-150-739-567",
  "authorised": "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
  "function": "Main Site",
  "salesDealerFlag": "Y",
  "fullXtimeParticipant": "Y",
  "consumerURL": "http://consumer.xtime.com/xt/scheduling/?webKey=aus201406271236&Provider=FORDAUPORTAL&Keyword=",
  "mobileURL": "http://consumer.xtime.com/xt/scheduling/?webKey=aus201406271236&Provider=FORDAUPORTAL&Keyword="
},{
  "dealerOrder": "",
  "cityOrder": "",
  "dealerCategory": "",
  "addressLine1": "12 Arncliffe St",
  "addressLine2": "",
  "articleId": "",
  "award": "",
  "city": "Arncliffe",
  "country": "",
  "dealerCode": "28011",
  "dealerInfo": "28011#@##@#City Ford (Parts Dist)",
  "dealershipName": "City Ford (Parts Dist)",
  "email": "reception@cityford.com.au",
  "fax": "02-9599 8062",
  "pma": "N/A",
  "localDealerCode": "",
  "name": "",
  "pageId": "",
  "phoneNumber1": "02-8577 4777",
  "phoneNumber2": "",
  "postcode": "2205",
  "state": "NSW",
  "website": "www.cityford.com.au",
  "abn": "84-088-817-912",
  "authorised": "CPS Participating, Parts, Service",
  "function": "Parts Warehouse",
  "salesDealerFlag": "",
  "fullXtimeParticipant": "N",
  "consumerURL": "",
  "mobileURL": ""
},{
  "dealerOrder": "",
  "cityOrder": "",
  "dealerCategory": "",
  "addressLine1": "12 Arncliffe Street",
  "addressLine2": "",
  "articleId": "",
  "award": "",
  "city": "Arncliffe",
  "country": "",
  "dealerCode": "28181",
  "dealerInfo": "28181#@##@#City Ford - Rockdale",
  "dealershipName": "City Ford - Rockdale",
  "email": "info@cityfordrockdale.com.au",
  "fax": "02-9599-8061",
  "pma": "N/A",
  "localDealerCode": "",
  "name": "",
  "pageId": "",
  "phoneNumber1": "1300 857 837",
  "phoneNumber2": "",
  "postcode": "2205",
  "state": "NSW",
  "website": "www.cityfordrockdale.com.au",
  "abn": "84-088-817-912",
  "authorised": "CPS Participating, Service",
  "function": "Service Branch Only",
  "salesDealerFlag": "",
  "fullXtimeParticipant": "N",
  "consumerURL": "",
  "mobileURL": ""
},{
  "dealerOrder": "",
  "cityOrder": "",
  "dealerCategory": "",
  "addressLine1": "267-275 Princes Hwy",
  "addressLine2": "",
  "articleId": "",
  "award": "",
  "city": "Rockdale",
  "country": "",
  "dealerCode": "28180",
  "dealerInfo": "28180#@##@#City Ford - Rockdale",
  "dealershipName": "City Ford - Rockdale",
  "email": "info@cityfordrockdale.com.au",
  "fax": "02-9599 7006",
  "pma": "N/A",
  "localDealerCode": "",
  "name": "",
  "pageId": "",
  "phoneNumber1": "02-8577 4111",
  "phoneNumber2": "",
  "postcode": "2216",
  "state": "NSW",
  "website": "www.cityfordrockdale.com.au",
  "abn": "84-088-817-912",
  "authorised": "CPS Participating, New Cars, Parts, Service, Used Cars",
  "function": "Main Site",
  "salesDealerFlag": "",
  "fullXtimeParticipant": "N",
  "consumerURL": "",
  "mobileURL": ""
},{
  "dealerOrder": "",
  "cityOrder": "",
  "dealerCategory": "",
  "addressLine1": "84 Moore Street",
  "addressLine2": "",
  "articleId": "",
  "award": "",
  "city": "Moe",
  "country": "",
  "dealerCode": "35981",
  "dealerInfo": "35981#@##@#Moe City Ford",
  "dealershipName": "Moe City Ford",
  "email": "contact@moecityford.com.au",
  "fax": "03-5127 6440",
  "pma": "N/A",
  "localDealerCode": "",
  "name": "",
  "pageId": "",
  "phoneNumber1": "03-5120 1777",
  "phoneNumber2": "",
  "postcode": "3825",
  "state": "VIC",
  "website": "www.moecityford.com.au",
  "abn": "33-956-021-589",
  "authorised": "CPS Participating, New Cars, Parts, Service, Used Cars",
  "function": "Full Branch",
  "salesDealerFlag": "",
  "fullXtimeParticipant": "N",
  "consumerURL": "",
  "mobileURL": ""
},{
  "dealerOrder": "",
  "cityOrder": "",
  "dealerCategory": "",
  "addressLine1": "1 Benaraby Road",
  "addressLine2": "",
  "articleId": "",
  "award": "",
  "city": "South Gladstone",
  "country": "",
  "dealerCode": "13280",
  "dealerInfo": "13280#@##@#Reef City Ford",
  "dealershipName": "Reef City Ford",
  "email": "gladstone@reefcityford.com.au",
  "fax": "07-4979 2242",
  "pma": "N/A",
  "localDealerCode": "",
  "name": "",
  "pageId": "",
  "phoneNumber1": "07-4971 4000",
  "phoneNumber2": "",
  "postcode": "4680",
  "state": "QLD",
  "website": "",
  "abn": "40-116-219-576",
  "authorised": "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
  "function": "Main Site",
  "salesDealerFlag": "Y",
  "fullXtimeParticipant": "N",
  "consumerURL": "",
  "mobileURL": ""
},{
  "dealerOrder": "",
  "cityOrder": "",
  "dealerCategory": "",
  "addressLine1": "11 Pearse Street",
  "addressLine2": "",
  "articleId": "",
  "award": "",
  "city": "Warragul",
  "country": "",
  "dealerCode": "35600",
  "dealerInfo": "35600#@##@#Warragul City Ford",
  "dealershipName": "Warragul City Ford",
  "email": "",
  "fax": "03-5623 4416",
  "pma": "N/A",
  "localDealerCode": "",
  "name": "",
  "pageId": "",
  "phoneNumber1": "03-5623-5633",
  "phoneNumber2": "",
  "postcode": "3820",
  "state": "VIC",
  "website": "",
  "abn": "64-149-117-877",
  "authorised": "CPS Participating, New Cars, Parts, Service, Used Cars",
  "function": "Main Site",
  "salesDealerFlag": "",
  "fullXtimeParticipant": "Y",
  "consumerURL": "",
  "mobileURL": ""
}
]