financialCalculator.config(['$routeProvider','routeConstants',function($routeProvider,routeConstants){
	$routeProvider
		.when(routeConstants.home.path,{
			template:routeConstants.home.template,
			controller:routeConstants.home.controller
		}).when(routeConstants.calculate.path,{
			template:routeConstants.calculate.template,
			controller:routeConstants.calculate.controller
		}).otherwise({
			redirectTo:routeConstants.home.path
		});
}]);
