[{
  "dealerOrder": "",
  "cityOrder": "",
  "dealerCategory": "",
  "addressLine1": "134 Elizabeth Street",
  "addressLine2": "",
  "articleId": "",
  "award": "",
  "city": "Sydney",
  "country": "",
  "dealerCode": "11111",
  "dealerInfo": "36220#@##@#City Ford",
  "dealershipName": "City Ford",
  "email": "info@city-ford.com.au",
  "fax": "03-9347 4635",
  "pma": "N/A","latitudeLongitude":{
    "latitude": -33.819829,
    "longitude": 151.003929,
    "locationName": "",
    "confidence": ""
  },
  "localDealerCode": "",
  "name": "",
  "pageId": "",
  "phoneNumber1": "03-9349 1277",
  "phoneNumber2": "",
  "postcode": "3000",
  "state": "VIC",
  "website": "www.city-ford.com.au",
  "abn": "82-150-739-567",
  "authorised": "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
  "function": "Main Site",
  "salesDealerFlag": "Y",
  "fullXtimeParticipant": "Y",
  "consumerURL": "http://consumer.xtime.com/xt/scheduling/?webKey=aus201404031235&Provider=FORDAUPORTAL&Keyword=",
  "mobileURL": "http://consumer.xtime.com/xt/scheduling/?webKey=aus201404031235&Provider=FORDAUPORTAL&Keyword="
},
{
  "dealerOrder": "",
  "cityOrder": "",
  "dealerCategory": "",
  "addressLine1": "334 Elizabeth Street",
  "addressLine2": "",
  "articleId": "",
  "award": "",
  "city": "Melbourne",
  "country": "",
  "dealerCode": "22222",
  "dealerInfo": "36220#@##@#City Ford",
  "dealershipName": "City Ford",
  "email": "info@city-ford.com.au",
  "fax": "03-9347 4635",
  "pma": "N/A","latitudeLongitude":{
    "latitude": -33.819829,
    "longitude": 151.003929,
    "locationName": "",
    "confidence": ""
  },
  "localDealerCode": "",
  "name": "",
  "pageId": "",
  "phoneNumber1": "03-9349 1278",
  "phoneNumber2": "",
  "postcode": "3000",
  "state": "VIC",
  "website": "www.city-ford.com.au",
  "abn": "82-150-739-567",
  "authorised": "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
  "function": "Main Site",
  "salesDealerFlag": "Y",
  "fullXtimeParticipant": "N",
  "consumerURL": "http://consumer.xtime.com/xt/scheduling/?webKey=aus201404031235&Provider=FORDAUPORTAL&Keyword=",
  "mobileURL": "http://consumer.xtime.com/xt/scheduling/?webKey=aus201404031235&Provider=FORDAUPORTAL&Keyword="
},
{
  "dealerOrder": "",
  "cityOrder": "",
  "dealerCategory": "",
  "addressLine1": "734 Elizabeth Street",
  "addressLine2": "",
  "articleId": "",
  "award": "",
  "city": "Brisbane",
  "country": "",
  "dealerCode": "33333",
  "dealerInfo": "36220#@##@#City Ford",
  "dealershipName": "City Ford",
  "email": "info@city-ford.com.au",
  "fax": "03-9347 4635",
  "pma": "N/A","latitudeLongitude":{
    "latitude": -33.819829,
    "longitude": 151.003929,
    "locationName": "",
    "confidence": ""
  },
  "localDealerCode": "",
  "name": "",
  "pageId": "",
  "phoneNumber1": "03-9349 1277",
  "phoneNumber2": "",
  "postcode": "3000",
  "state": "VIC",
  "website": "www.city-ford.com.au",
  "abn": "82-150-739-567",
  "authorised": "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
  "function": "Main Site",
  "salesDealerFlag": "Y",
  "fullXtimeParticipant": "Y",
  "consumerURL": "http://consumer.xtime.com/xt/scheduling/?webKey=aus201404031235&Provider=FORDAUPORTAL&Keyword=",
  "mobileURL": "http://consumer.xtime.com/xt/scheduling/?webKey=aus201404031235&Provider=FORDAUPORTAL&Keyword="
}]