[ {
    "name" : null,
    "country" : null,
    "dealerCode" : "36600",
    "localDealerCode" : "",
    "dealershipName" : "Aberlines Garage",
    "addressLine1" : "88-90 Main Street",
    "addressLine2" : null,
    "postcode" : "2671",
    "phoneNumber1" : "02-6972 2001",
    "phoneNumber2" : null,
    "fax" : "02-6972 2927",
    "website" : "",
    "email" : "abbeford@bigpond.net.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "West Wyalong",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "44-001-843-938",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "36600#@##@#Aberlines Garage",
    "latitudeLongitude" : {
        "latitude" : -33.923595,
        "longitude" : 147.207357,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "22200",
    "localDealerCode" : "",
    "dealershipName" : "Alpine Ford",
    "addressLine1" : "28-32 Bombala Street",
    "addressLine2" : null,
    "postcode" : "2630",
    "phoneNumber1" : "02-6452 1044",
    "phoneNumber2" : null,
    "fax" : "02-6452 1436",
    "website" : "",
    "email" : "alpineford@bigpond.com",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Cooma",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "68-074-547-238",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "22200#@##@#Alpine Ford",
    "latitudeLongitude" : {
        "latitude" : -36.235015,
        "longitude" : 149.127845,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25350",
    "localDealerCode" : "",
    "dealershipName" : "Andrew Miedecke Ford",
    "addressLine1" : "100 Hastings River Drive",
    "addressLine2" : null,
    "postcode" : "2444",
    "phoneNumber1" : "02-6583 8855",
    "phoneNumber2" : null,
    "fax" : "02-6583 8341",
    "website" : "www.miedecke.com.au",
    "email" : "amiedecke@miedecke.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Port Macquarie",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "50-002-582-621",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25350#@##@#Andrew Miedecke Ford",
    "latitudeLongitude" : {
        "latitude" : -31.429249,
        "longitude" : 152.882726,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "24380",
    "localDealerCode" : "",
    "dealershipName" : "Barry's Motors",
    "addressLine1" : "199 Byron Street",
    "addressLine2" : null,
    "postcode" : "2360",
    "phoneNumber1" : "02-6722 1433",
    "phoneNumber2" : null,
    "fax" : "02-6722 5316",
    "website" : "",
    "email" : "doug@barrysmotors.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Inverell",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "50-000-544-650",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "24380#@##@#Barry's Motors",
    "latitudeLongitude" : {
        "latitude" : -29.770347,
        "longitude" : 151.117082,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "34360",
    "localDealerCode" : "",
    "dealershipName" : "Belmore Motors",
    "addressLine1" : "4 Belmore Street",
    "addressLine2" : null,
    "postcode" : "2663",
    "phoneNumber1" : "02-6924-1996",
    "phoneNumber2" : null,
    "fax" : "02-6924-1330",
    "website" : "",
    "email" : "waynewatterson.belmoremotors@hotmail.com",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Junee",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "18-559-234-198",
    "authorised" : "CPS Participating, Parts, Service, Used Cars",
    "function" : "Parts & Service Dealer",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "34360#@##@#Belmore Motors",
    "latitudeLongitude" : {
        "latitude" : -34.871288,
        "longitude" : 147.585037,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "34400",
    "localDealerCode" : "",
    "dealershipName" : "Biti Motors",
    "addressLine1" : "35 Balfour Street",
    "addressLine2" : null,
    "postcode" : "2660",
    "phoneNumber1" : "02-6029 8279",
    "phoneNumber2" : null,
    "fax" : "02-6029 8702",
    "website" : "",
    "email" : "bitimotors@hotkey.net.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Culcairn",
    "state" : "NSW",
    "pma" : "S25",
    "abn" : "63-002-083-703",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "34400#@##@#Biti Motors",
    "latitudeLongitude" : {
        "latitude" : -35.668249,
        "longitude" : 147.037359,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "34011",
    "localDealerCode" : "",
    "dealershipName" : "Blacklocks Ford",
    "addressLine1" : "Cnr. Kaitlers & Wagga Roads",
    "addressLine2" : null,
    "postcode" : "2641",
    "phoneNumber1" : "02-6049 5500",
    "phoneNumber2" : null,
    "fax" : "02-6040 4545",
    "website" : "",
    "email" : "sales@blacklocks.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Albury",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Full Branch",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "34011#@##@#Blacklocks Ford",
    "latitudeLongitude" : {
        "latitude" : -36.036691,
        "longitude" : 146.965886,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "28040",
    "localDealerCode" : "",
    "dealershipName" : "Brad Garlick Ford",
    "addressLine1" : "2-16 Blaxland Road",
    "addressLine2" : null,
    "postcode" : "2112",
    "phoneNumber1" : "02-9807 2933",
    "phoneNumber2" : null,
    "fax" : "02-9808 2501",
    "website" : "www.bradgarlick.com.au",
    "email" : "reception@bradgarlick.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Ryde",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "84-088-817-912",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "28040#@##@#Brad Garlick Ford",
    "latitudeLongitude" : {
        "latitude" : -33.815932,
        "longitude" : 151.108429,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25180",
    "localDealerCode" : "",
    "dealershipName" : "Central Coast Ford",
    "addressLine1" : "14 Central Coast Highway",
    "addressLine2" : null,
    "postcode" : "2250",
    "phoneNumber1" : "02-4321 6265",
    "phoneNumber2" : null,
    "fax" : "02-4321 6293",
    "website" : "www.centralcoastford.com.au",
    "email" : "",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "West Gosford",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "44-150-442-872",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25180#@##@#Central Coast Ford",
    "latitudeLongitude" : {
        "latitude" : -33.427585,
        "longitude" : 151.325046,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25490",
    "localDealerCode" : "",
    "dealershipName" : "Cessnock Ford",
    "addressLine1" : "206 Wollombi Road",
    "addressLine2" : null,
    "postcode" : "2325",
    "phoneNumber1" : "02-4991-5220",
    "phoneNumber2" : null,
    "fax" : "02-4991-7220",
    "website" : "",
    "email" : "",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Cessnock",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "77-081-910-983",
    "authorised" : "CPS Non-participating, New Cars, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25490#@##@#Cessnock Ford",
    "latitudeLongitude" : {
        "latitude" : -32.833092,
        "longitude" : 151.352646,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25491",
    "localDealerCode" : "",
    "dealershipName" : "Cessnock Ford",
    "addressLine1" : "Unit 7 353 Maitland Road",
    "addressLine2" : null,
    "postcode" : "2325",
    "phoneNumber1" : "02-4990-2774",
    "phoneNumber2" : null,
    "fax" : "02-4990-5299",
    "website" : "",
    "email" : "",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Cessnock",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "77-081-910-983",
    "authorised" : "CPS Non-participating, Parts, Service",
    "function" : "Parts & Service Branch",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25491#@##@#Cessnock Ford",
    "latitudeLongitude" : {
        "latitude" : -32.828587,
        "longitude" : 151.371994,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "28010",
    "localDealerCode" : "",
    "dealershipName" : "City Ford",
    "addressLine1" : "811 Elizabeth St",
    "addressLine2" : null,
    "postcode" : "2017",
    "phoneNumber1" : "02-9331 5000",
    "phoneNumber2" : null,
    "fax" : "02-9332 8195",
    "website" : "www.cityford.com.au",
    "email" : "reception@cityford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Zetland",
    "state" : "NSW",
    "pma" : "E53",
    "abn" : "84-088-817-912",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "28010#@##@#City Ford",
    "latitudeLongitude" : {
        "latitude" : -33.90728,
        "longitude" : 151.20694,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "28012",
    "localDealerCode" : "",
    "dealershipName" : "City Ford",
    "addressLine1" : "204 Hume Highway",
    "addressLine2" : null,
    "postcode" : "2190",
    "phoneNumber1" : "02-9642 0385",
    "phoneNumber2" : null,
    "fax" : "02-9742 5070",
    "website" : "www.cityford.com.au",
    "email" : "reception@cityford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Chullora",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "84-088-817-912",
    "authorised" : "CPS Participating, Used Cars",
    "function" : "Used Vehicles Only",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "28012#@##@#City Ford",
    "latitudeLongitude" : {
        "latitude" : -33.89095,
        "longitude" : 151.057513,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "28011",
    "localDealerCode" : "",
    "dealershipName" : "City Ford (Parts Dist)",
    "addressLine1" : "12 Arncliffe St",
    "addressLine2" : null,
    "postcode" : "2205",
    "phoneNumber1" : "02-8577 4777",
    "phoneNumber2" : null,
    "fax" : "02-9599 8062",
    "website" : "www.cityford.com.au",
    "email" : "reception@cityford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Arncliffe",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "84-088-817-912",
    "authorised" : "CPS Participating, Parts, Service",
    "function" : "Parts Warehouse",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "28011#@##@#City Ford (Parts Dist)",
    "latitudeLongitude" : {
        "latitude" : -33.933772,
        "longitude" : 151.149932,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "28181",
    "localDealerCode" : "",
    "dealershipName" : "City Ford - Rockdale",
    "addressLine1" : "12 Arncliffe Street",
    "addressLine2" : null,
    "postcode" : "2205",
    "phoneNumber1" : "1300 857 837",
    "phoneNumber2" : null,
    "fax" : "02-9599-8061",
    "website" : "www.cityfordrockdale.com.au",
    "email" : "info@cityfordrockdale.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Arncliffe",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "84-088-817-912",
    "authorised" : "CPS Participating, Service",
    "function" : "Service Branch Only",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "28181#@##@#City Ford - Rockdale",
    "latitudeLongitude" : {
        "latitude" : -33.933772,
        "longitude" : 151.149932,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "28180",
    "localDealerCode" : "",
    "dealershipName" : "City Ford - Rockdale",
    "addressLine1" : "267-275 Princes Hwy",
    "addressLine2" : null,
    "postcode" : "2216",
    "phoneNumber1" : "02-8577 4111",
    "phoneNumber2" : null,
    "fax" : "02-9599 7006",
    "website" : "www.cityfordrockdale.com.au",
    "email" : "info@cityfordrockdale.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Rockdale",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "84-088-817-912",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "28180#@##@#City Ford - Rockdale",
    "latitudeLongitude" : {
        "latitude" : -33.95419,
        "longitude" : 151.137618,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "23020",
    "localDealerCode" : "",
    "dealershipName" : "Clancy Ford",
    "addressLine1" : "250 Howick Street",
    "addressLine2" : null,
    "postcode" : "2795",
    "phoneNumber1" : "02-6339 9444",
    "phoneNumber2" : null,
    "fax" : "02-6339 9440",
    "website" : "www.clancymotors.com.au",
    "email" : "vehicles@clancymotors.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Bathurst",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "28-124-607-861",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "23020#@##@#Clancy Ford",
    "latitudeLongitude" : {
        "latitude" : -33.41521,
        "longitude" : 149.578879,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "24210",
    "localDealerCode" : "",
    "dealershipName" : "Clancy Ford Dubbo",
    "addressLine1" : "94-100 Wheelers Lane",
    "addressLine2" : null,
    "postcode" : "2830",
    "phoneNumber1" : "02-6884 9755",
    "phoneNumber2" : null,
    "fax" : "02-6882 5752",
    "website" : "www.clancyautomotive.com.au",
    "email" : "enquire@clancyautomotive.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Dubbo",
    "state" : "NSW",
    "pma" : "E30",
    "abn" : "34-134-034-209",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "24210#@##@#Clancy Ford Dubbo",
    "latitudeLongitude" : {
        "latitude" : -32.253314,
        "longitude" : 148.629956,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "23440",
    "localDealerCode" : "",
    "dealershipName" : "Col Fletcher Ford",
    "addressLine1" : "378 Clarinda Street",
    "addressLine2" : null,
    "postcode" : "2870",
    "phoneNumber1" : "02-6862 3222",
    "phoneNumber2" : null,
    "fax" : "02-6862 3265",
    "website" : "",
    "email" : "fletcherford@bigpond.com",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Parkes",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "14-102-243-676",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "23440#@##@#Col Fletcher Ford",
    "latitudeLongitude" : {
        "latitude" : -33.131247,
        "longitude" : 148.173355,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25100",
    "localDealerCode" : "",
    "dealershipName" : "Conrad Ford",
    "addressLine1" : "129-145 Imlay Street",
    "addressLine2" : null,
    "postcode" : "2551",
    "phoneNumber1" : "02-6496 1529",
    "phoneNumber2" : null,
    "fax" : "02-6496 3219",
    "website" : "",
    "email" : "frasmot@bigpond.net.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Eden",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "59-001-380-605",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25100#@##@#Conrad Ford",
    "latitudeLongitude" : {
        "latitude" : -37.062056,
        "longitude" : 149.904439,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "24251",
    "localDealerCode" : "",
    "dealershipName" : "Cook & Black Auto Repairs",
    "addressLine1" : "60 Morrison Street",
    "addressLine2" : null,
    "postcode" : "2835",
    "phoneNumber1" : "02-6836 1533",
    "phoneNumber2" : null,
    "fax" : "02-6836 1668",
    "website" : "",
    "email" : "",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Cobar",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "",
    "authorised" : "CPS Participating, Service",
    "function" : "Parts & Service Sub Agent",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "24251#@##@#Cook & Black Auto Repairs",
    "latitudeLongitude" : {
        "latitude" : -31.497527,
        "longitude" : 145.830353,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "23230",
    "localDealerCode" : "",
    "dealershipName" : "Cowra Motors",
    "addressLine1" : "37-39 Young Road",
    "addressLine2" : null,
    "postcode" : "2794",
    "phoneNumber1" : "02-6341 2000",
    "phoneNumber2" : null,
    "fax" : "02-6342 3990",
    "website" : "www.cowramotors.com.au",
    "email" : "cowramotors@cowramotors.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Cowra",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "40-116-929-563",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "23230#@##@#Cowra Motors",
    "latitudeLongitude" : {
        "latitude" : -33.841182,
        "longitude" : 148.675028,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25770",
    "localDealerCode" : "",
    "dealershipName" : "Cross Country Ford",
    "addressLine1" : "147 Bridge Street",
    "addressLine2" : null,
    "postcode" : "2333",
    "phoneNumber1" : "02-6543 3277",
    "phoneNumber2" : null,
    "fax" : "02-6542 5599",
    "website" : "",
    "email" : "ccf@crosscountryford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Muswellbrook",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "87-001-999-284",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25770#@##@#Cross Country Ford",
    "latitudeLongitude" : {
        "latitude" : -32.259096,
        "longitude" : 150.89007,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "28130",
    "localDealerCode" : "",
    "dealershipName" : "Cumberland Ford",
    "addressLine1" : "145-151 Main Street",
    "addressLine2" : null,
    "postcode" : "2148",
    "phoneNumber1" : "02-9622 0400",
    "phoneNumber2" : null,
    "fax" : "02-9831 4651",
    "website" : "www.cumberlandford.com.au",
    "email" : "reception@cumberlandford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Blacktown",
    "state" : "NSW",
    "pma" : "E64",
    "abn" : "84-088-817-912",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "28130#@##@#Cumberland Ford",
    "latitudeLongitude" : {
        "latitude" : -33.772425,
        "longitude" : 150.914069,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "24510",
    "localDealerCode" : "",
    "dealershipName" : "D & J Ford",
    "addressLine1" : "75 Chifley Road",
    "addressLine2" : null,
    "postcode" : "2790",
    "phoneNumber1" : "02-6352 2644",
    "phoneNumber2" : null,
    "fax" : "02-6352 3505",
    "website" : "www.djford.com.au",
    "email" : "info@djford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Lithgow",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "37-124-676-384",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "24510#@##@#D & J Ford",
    "latitudeLongitude" : {
        "latitude" : -33.47818,
        "longitude" : 150.173001,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25090",
    "localDealerCode" : "",
    "dealershipName" : "Davey and Olsen",
    "addressLine1" : "160-168 Dowling Street",
    "addressLine2" : null,
    "postcode" : "2420",
    "phoneNumber1" : "02-4992 1476",
    "phoneNumber2" : null,
    "fax" : "02-4992 3083",
    "website" : "",
    "email" : "dando@bravo.net.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Dungog",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "65-000-127-551",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25090#@##@#Davey and Olsen",
    "latitudeLongitude" : {
        "latitude" : -32.40259,
        "longitude" : 151.757264,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "15390",
    "localDealerCode" : "",
    "dealershipName" : "Des Watson Ford",
    "addressLine1" : "2-4 Summerland Way",
    "addressLine2" : null,
    "postcode" : "2474",
    "phoneNumber1" : "02-6632 2100",
    "phoneNumber2" : null,
    "fax" : "02-6632 2044",
    "website" : "",
    "email" : "admin@deswatsonford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Kyogle",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "16-002-793-900",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "15390#@##@#Des Watson Ford",
    "latitudeLongitude" : {
        "latitude" : -28.616772,
        "longitude" : 153.00343,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "21550",
    "localDealerCode" : "",
    "dealershipName" : "Dominelli Ford",
    "addressLine1" : "579 Princes Highway",
    "addressLine2" : null,
    "postcode" : "2232",
    "phoneNumber1" : "02-9545 9000",
    "phoneNumber2" : null,
    "fax" : "02-9521 3046",
    "website" : "www.dominelli.com.au",
    "email" : "newenquiry@dominelli.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Kirrawee",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "49-002-523-097",
    "authorised" : "CPS Participating, New Cars, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "21550#@##@#Dominelli Ford",
    "latitudeLongitude" : {
        "latitude" : -34.032297,
        "longitude" : 151.07299,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "21551",
    "localDealerCode" : "",
    "dealershipName" : "Dominelli Ford",
    "addressLine1" : "53-57 Waratah Street",
    "addressLine2" : null,
    "postcode" : "2232",
    "phoneNumber1" : "02-9545 9090",
    "phoneNumber2" : null,
    "fax" : "02-9521 3046",
    "website" : "www.dominelli.com.au",
    "email" : "newenquiry@dominelli.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Kirrawee",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "49-002-523-097",
    "authorised" : "CPS Participating, Parts, Service",
    "function" : "Parts & Service Branch",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "21551#@##@#Dominelli Ford",
    "latitudeLongitude" : {
        "latitude" : -34.028306,
        "longitude" : 151.075748,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "24690",
    "localDealerCode" : "",
    "dealershipName" : "Duncan and Duncan",
    "addressLine1" : "4 Fox Street",
    "addressLine2" : null,
    "postcode" : "2832",
    "phoneNumber1" : "02-6828 1197",
    "phoneNumber2" : null,
    "fax" : "02-6828 2070",
    "website" : "",
    "email" : "dndwalgett@bigpond.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Walgett",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "47-066-098-039",
    "authorised" : "CPS Non-participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "24690#@##@#Duncan and Duncan",
    "latitudeLongitude" : {
        "latitude" : -30.017636,
        "longitude" : 148.116951,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25780",
    "localDealerCode" : "",
    "dealershipName" : "E.L.N. Ford",
    "addressLine1" : "136 - 140 Pacific Highway",
    "addressLine2" : null,
    "postcode" : "2259",
    "phoneNumber1" : "02-4350 4333",
    "phoneNumber2" : null,
    "fax" : "02-4350 4335",
    "website" : "www.elnford.com.au",
    "email" : "sales@elnford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Tuggerah",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "54-497-370-529",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25780#@##@#E.L.N. Ford",
    "latitudeLongitude" : {
        "latitude" : -33.302127,
        "longitude" : 151.420729,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "43070",
    "localDealerCode" : "",
    "dealershipName" : "Far West Ford",
    "addressLine1" : "184-190 Crystal Street",
    "addressLine2" : null,
    "postcode" : "2880",
    "phoneNumber1" : "08-8087 2311",
    "phoneNumber2" : null,
    "fax" : "08-8088 5835",
    "website" : "",
    "email" : "vanessa@farwestauto.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Broken Hill",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "41-466-404-365",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "43070#@##@#Far West Ford",
    "latitudeLongitude" : {
        "latitude" : -31.960694,
        "longitude" : 141.463797,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "15240",
    "localDealerCode" : "",
    "dealershipName" : "Fitzgerald Ford",
    "addressLine1" : "14 Cudgery Street",
    "addressLine2" : null,
    "postcode" : "2453",
    "phoneNumber1" : "02-6657 2160",
    "phoneNumber2" : null,
    "fax" : "02-6657 2731",
    "website" : "",
    "email" : "fitzford@bigpond.net.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Dorrigo",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "37-002-591-979",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "15240#@##@#Fitzgerald Ford",
    "latitudeLongitude" : {
        "latitude" : -30.340107,
        "longitude" : 152.712603,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "28300",
    "localDealerCode" : "",
    "dealershipName" : "Goulburn Ford",
    "addressLine1" : "128-130 Hume Street",
    "addressLine2" : null,
    "postcode" : "2580",
    "phoneNumber1" : "02-4823 1000",
    "phoneNumber2" : null,
    "fax" : "02-4823 1066",
    "website" : "",
    "email" : "administration@jmcg.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Goulburn",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "78-093-024-107",
    "authorised" : "CPS Participating, New Cars, Parts, Service",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "28300#@##@#Goulburn Ford",
    "latitudeLongitude" : {
        "latitude" : -34.770218,
        "longitude" : 149.694629,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "24980",
    "localDealerCode" : "",
    "dealershipName" : "Grant McCarroll Ford",
    "addressLine1" : "125 Marsh Street",
    "addressLine2" : null,
    "postcode" : "2350",
    "phoneNumber1" : "02-6772 1566",
    "phoneNumber2" : null,
    "fax" : "02-6772 8272",
    "website" : "",
    "email" : "grant@gmford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Armidale",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "85-058-431-986",
    "authorised" : "CPS Non-participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "24980#@##@#Grant McCarroll Ford",
    "latitudeLongitude" : {
        "latitude" : -30.515326,
        "longitude" : 151.668822,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "22580",
    "localDealerCode" : "",
    "dealershipName" : "Harrigan Ford",
    "addressLine1" : "46-54 Princes Highway",
    "addressLine2" : null,
    "postcode" : "2530",
    "phoneNumber1" : "02-4230 8888",
    "phoneNumber2" : null,
    "fax" : "02-4257 0707",
    "website" : "www.harriganford.com.au",
    "email" : "belliott@harrigan.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Yallah",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "26-112-693-562",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "22580#@##@#Harrigan Ford",
    "latitudeLongitude" : {
        "latitude" : -34.542021,
        "longitude" : 150.783771,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "21090",
    "localDealerCode" : "",
    "dealershipName" : "Heartland Ford",
    "addressLine1" : "273 Hume highway",
    "addressLine2" : null,
    "postcode" : "2190",
    "phoneNumber1" : "02-9708-8999",
    "phoneNumber2" : null,
    "fax" : "02-9708-8990",
    "website" : "www.heartland.com.au",
    "email" : "nduggin@heartland.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Greenacre",
    "state" : "NSW",
    "pma" : "E60",
    "abn" : "57-096-561-385",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "21090#@##@#Heartland Ford",
    "latitudeLongitude" : {
        "latitude" : -33.903278,
        "longitude" : 151.043671,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25440",
    "localDealerCode" : "",
    "dealershipName" : "Highway Ford",
    "addressLine1" : "194-196 New England Highway",
    "addressLine2" : null,
    "postcode" : "2320",
    "phoneNumber1" : "02-4937 7500",
    "phoneNumber2" : null,
    "fax" : "02-4937 7510",
    "website" : "www.highwaycars.com.au",
    "email" : "new.sales@highwaycars.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Maitland",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "80-000-868-860",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25440#@##@#Highway Ford",
    "latitudeLongitude" : {
        "latitude" : -32.718832,
        "longitude" : 151.532858,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "34640",
    "localDealerCode" : "",
    "dealershipName" : "Hillis Ford",
    "addressLine1" : "41-43 Hammond Avenue",
    "addressLine2" : null,
    "postcode" : "2650",
    "phoneNumber1" : "02-6923 1100",
    "phoneNumber2" : null,
    "fax" : "02-6921 8069",
    "website" : "www.hillisford.com.au",
    "email" : "hillis@hillis.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Wagga Wagga",
    "state" : "NSW",
    "pma" : "S55",
    "abn" : "21-000-563-155",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "34640#@##@#Hillis Ford",
    "latitudeLongitude" : {
        "latitude" : -35.120336,
        "longitude" : 147.382999,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "23140",
    "localDealerCode" : "",
    "dealershipName" : "J.R. Sealey Pty Ltd",
    "addressLine1" : "28 William Street",
    "addressLine2" : null,
    "postcode" : "2877",
    "phoneNumber1" : "02-6895 2209",
    "phoneNumber2" : null,
    "fax" : "02-6895 2036",
    "website" : "www.jrsealey.com",
    "email" : "jrsealey@autogrid.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Condobolin",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "83-000-166-576",
    "authorised" : "CPS Non-participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "23140#@##@#J.R. Sealey Pty Ltd",
    "latitudeLongitude" : {
        "latitude" : -33.089173,
        "longitude" : 147.146648,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25600",
    "localDealerCode" : "",
    "dealershipName" : "J.T. Fossey",
    "addressLine1" : "501 Peel Street",
    "addressLine2" : null,
    "postcode" : "2340",
    "phoneNumber1" : "02-6766 1466",
    "phoneNumber2" : null,
    "fax" : "02-6766 8566",
    "website" : "www.jtfossey.com.au",
    "email" : "john.keating@jtfossey.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Tamworth",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "78-000-178-272",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25600#@##@#J.T. Fossey",
    "latitudeLongitude" : {
        "latitude" : -31.094687,
        "longitude" : 150.9334,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "23442",
    "localDealerCode" : "",
    "dealershipName" : "Jelbart, Dawson & Company",
    "addressLine1" : "7 Oxford Street",
    "addressLine2" : null,
    "postcode" : "2871",
    "phoneNumber1" : "02-6851 1640",
    "phoneNumber2" : null,
    "fax" : "02-6852 2401",
    "website" : "",
    "email" : "",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Forbes",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "",
    "authorised" : "CPS Participating, Parts, Service",
    "function" : "Parts & Service Sub Agent",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "23442#@##@#Jelbart, Dawson & Company",
    "latitudeLongitude" : {
        "latitude" : -33.394088,
        "longitude" : 148.004046,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "24710",
    "localDealerCode" : "",
    "dealershipName" : "Kaputar Ford",
    "addressLine1" : "5 Caroline Way",
    "addressLine2" : null,
    "postcode" : "2390",
    "phoneNumber1" : "02-6792 1816",
    "phoneNumber2" : null,
    "fax" : "02-6792 1806",
    "website" : "www.kaputarford.com.au",
    "email" : "enquiries@kaputarford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Narrabri",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "35-000-136-710",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "24710#@##@#Kaputar Ford",
    "latitudeLongitude" : {
        "latitude" : -30.310175,
        "longitude" : 149.780698,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "34220",
    "localDealerCode" : "",
    "dealershipName" : "Keith Gill Motors",
    "addressLine1" : "1 Ebert Street",
    "addressLine2" : null,
    "postcode" : "2680",
    "phoneNumber1" : "02-6964 1111",
    "phoneNumber2" : null,
    "fax" : "02-6964 1045",
    "website" : "www.keithgillmotors.com.au",
    "email" : "wgill@keithgillmotors.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Griffith",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "92-949-967-100",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "34220#@##@#Keith Gill Motors",
    "latitudeLongitude" : {
        "latitude" : -34.292494,
        "longitude" : 146.069223,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "15420",
    "localDealerCode" : "",
    "dealershipName" : "Kennwal Ford",
    "addressLine1" : "3 Pacific Hwy",
    "addressLine2" : null,
    "postcode" : "2448",
    "phoneNumber1" : "02-6568 7333",
    "phoneNumber2" : null,
    "fax" : "02-6568 8090",
    "website" : "",
    "email" : "kennwalsales@bigpond.com",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Nambucca Heads",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "43-002-457-098",
    "authorised" : "CPS Non-participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "15420#@##@#Kennwal Ford",
    "latitudeLongitude" : {
        "latitude" : -30.677772,
        "longitude" : 152.973798,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "22600",
    "localDealerCode" : "",
    "dealershipName" : "Kinghorn Motors",
    "addressLine1" : "Cnr. East & Junction Streets",
    "addressLine2" : null,
    "postcode" : "2541",
    "phoneNumber1" : "02-4421 4666",
    "phoneNumber2" : null,
    "fax" : "02-4423 1188",
    "website" : "www.kinghorn.com.au",
    "email" : "sales@kinghorn.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Nowra",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "33-000-220-557",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "22600#@##@#Kinghorn Motors",
    "latitudeLongitude" : {
        "latitude" : -34.874992,
        "longitude" : 150.605554,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25430",
    "localDealerCode" : "",
    "dealershipName" : "Kloster Ford",
    "addressLine1" : "Cnr. Tudor St. & Gordon Ave.",
    "addressLine2" : null,
    "postcode" : "2303",
    "phoneNumber1" : "02-4922 0500",
    "phoneNumber2" : null,
    "fax" : "02-4961 4607",
    "website" : "www.kloster.com.au",
    "email" : "mail@kloster.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Hamilton",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "80-000-868-860",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25430#@##@#Kloster Ford",
    "latitudeLongitude" : {
        "latitude" : -32.924647,
        "longitude" : 151.751485,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25431",
    "localDealerCode" : "",
    "dealershipName" : "Kloster Ford",
    "addressLine1" : "189 Pacific Highway",
    "addressLine2" : null,
    "postcode" : "2324",
    "phoneNumber1" : "02-4983 1566",
    "phoneNumber2" : null,
    "fax" : "02-4987 1400",
    "website" : "www.kloster.com.au",
    "email" : "mail@kloster.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Raymond Terrace",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "80-000-868-860",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Full Branch",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25431#@##@#Kloster Ford",
    "latitudeLongitude" : {
        "latitude" : -32.756071,
        "longitude" : 151.765524,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25450",
    "localDealerCode" : "",
    "dealershipName" : "Lake Ford",
    "addressLine1" : "2-16 Taylor Street",
    "addressLine2" : null,
    "postcode" : "2285",
    "phoneNumber1" : "02-4014 9900",
    "phoneNumber2" : null,
    "fax" : "02-4954 5868",
    "website" : "www.kloster.com.au",
    "email" : "cardiff.sales@kloster.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Cardiff",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "80-000-868-860",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25450#@##@#Lake Ford",
    "latitudeLongitude" : {
        "latitude" : -32.937574,
        "longitude" : 151.658728,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "34230",
    "localDealerCode" : "",
    "dealershipName" : "Lanham Ford",
    "addressLine1" : "5 Pine Avenue",
    "addressLine2" : null,
    "postcode" : "2705",
    "phoneNumber1" : "02-6953 3600",
    "phoneNumber2" : null,
    "fax" : "02-6953 4977",
    "website" : "",
    "email" : "lanham@dragnet.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Leeton",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "92-949-967-100",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "34230#@##@#Lanham Ford",
    "latitudeLongitude" : {
        "latitude" : -34.551613,
        "longitude" : 146.400043,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "21820",
    "localDealerCode" : "",
    "dealershipName" : "Macarthur Ford",
    "addressLine1" : "36 Blaxland Rd",
    "addressLine2" : null,
    "postcode" : "2560",
    "phoneNumber1" : "02-4645 8888",
    "phoneNumber2" : null,
    "fax" : "02-4645 8800",
    "website" : "www.macarthurford.com.au",
    "email" : "reception@macarthurford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Campbelltown",
    "state" : "NSW",
    "pma" : "E73",
    "abn" : "67-000-293-621",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "21820#@##@#Macarthur Ford",
    "latitudeLongitude" : {
        "latitude" : -34.060258,
        "longitude" : 150.813571,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "21810",
    "localDealerCode" : "",
    "dealershipName" : "Macarthur Ford",
    "addressLine1" : "12 Yarmouth Place",
    "addressLine2" : null,
    "postcode" : "2567",
    "phoneNumber1" : "02-4636 8888",
    "phoneNumber2" : null,
    "fax" : "02-4636 8889",
    "website" : "www.macarthurfordnarellan.com.au",
    "email" : "ebusiness@macarthurautomotive.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Narellan",
    "state" : "NSW",
    "pma" : "E72",
    "abn" : "67-000-293-621",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "21810#@##@#Macarthur Ford",
    "latitudeLongitude" : {
        "latitude" : -34.040836,
        "longitude" : 150.749751,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "23650",
    "localDealerCode" : "",
    "dealershipName" : "McAlister Motors",
    "addressLine1" : "9 Zouch Street",
    "addressLine2" : null,
    "postcode" : "2594",
    "phoneNumber1" : "02-6382 3033",
    "phoneNumber2" : null,
    "fax" : "02-6382 4179",
    "website" : "mcalistermotors.com.au",
    "email" : "hugh@mcalistermotors.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Young",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "76-616-463-902",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "23650#@##@#McAlister Motors",
    "latitudeLongitude" : {
        "latitude" : -34.309842,
        "longitude" : 148.300959,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "24590",
    "localDealerCode" : "",
    "dealershipName" : "McCarroll Motors",
    "addressLine1" : "11 Sydney Road",
    "addressLine2" : null,
    "postcode" : "2850",
    "phoneNumber1" : "02-6372 3288",
    "phoneNumber2" : null,
    "fax" : "02-6372 2920",
    "website" : "",
    "email" : "admin@mccarrollmotors.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Mudgee",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "76-152-997-405",
    "authorised" : "CPS Participating, New Cars, Part, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "24590#@##@#McCarroll Motors",
    "latitudeLongitude" : {
        "latitude" : -32.607609,
        "longitude" : 149.60022,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25840",
    "localDealerCode" : "",
    "dealershipName" : "Mid Coast Ford",
    "addressLine1" : "100 Manning River Drive",
    "addressLine2" : null,
    "postcode" : "2430",
    "phoneNumber1" : "02-6592 6300",
    "phoneNumber2" : null,
    "fax" : "02-6551 0450",
    "website" : "www.midcoastford.com.au",
    "email" : "sales@midcoastford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Taree North",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "76-002-897-903",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25840#@##@#Mid Coast Ford",
    "latitudeLongitude" : {
        "latitude" : -31.900916,
        "longitude" : 152.487892,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25841",
    "localDealerCode" : "",
    "dealershipName" : "Mid Coast Ford",
    "addressLine1" : "Lot 32 The Lakes Way",
    "addressLine2" : null,
    "postcode" : "2428",
    "phoneNumber1" : "02-6591 7933",
    "phoneNumber2" : null,
    "fax" : "02-5454 6663",
    "website" : "",
    "email" : "",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Forster",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "76-002-897-903",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Full Branch",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25841#@##@#Mid Coast Ford",
    "latitudeLongitude" : {
        "latitude" : -32.182302,
        "longitude" : 152.516781,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "15340",
    "localDealerCode" : "",
    "dealershipName" : "Mike Blewitt Ford",
    "addressLine1" : "Lot 3, Tolhurst Place",
    "addressLine2" : null,
    "postcode" : "2450",
    "phoneNumber1" : "02-6648 3566",
    "phoneNumber2" : null,
    "fax" : "02-6651 2400",
    "website" : "www.mikeblewitt.com.au",
    "email" : "stock@mikeblewitt.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Coffs Harbour",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "19-135-654-892",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "15340#@##@#Mike Blewitt Ford",
    "latitudeLongitude" : {
        "latitude" : -30.306664,
        "longitude" : 153.102291,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "34350",
    "localDealerCode" : "",
    "dealershipName" : "Palmer Ford",
    "addressLine1" : "70 Wallendoon Street",
    "addressLine2" : null,
    "postcode" : "2590",
    "phoneNumber1" : "02-6942 2970",
    "phoneNumber2" : null,
    "fax" : "02-6942 4826",
    "website" : "",
    "email" : "palmford@bigpond.net.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Cootamundra",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "25-502-283-993",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "34350#@##@#Palmer Ford",
    "latitudeLongitude" : {
        "latitude" : -34.640268,
        "longitude" : 148.026023,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "21570",
    "localDealerCode" : "",
    "dealershipName" : "Peter Warren Ford",
    "addressLine1" : "90-94 Warren Rd",
    "addressLine2" : null,
    "postcode" : "2164",
    "phoneNumber1" : "02-8724 1111",
    "phoneNumber2" : null,
    "fax" : "02-8724 1100",
    "website" : "www.peterwarrenspecial.com.au",
    "email" : "ebusiness@peterwarren.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Smithfield",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "67-000-293-621",
    "authorised" : "Body Shop, CPS Participating, Parts, Service, Used Cars",
    "function" : "Parts & Service Dealer",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "21570#@##@#Peter Warren Ford",
    "latitudeLongitude" : {
        "latitude" : -33.844611,
        "longitude" : 150.956972,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "21490",
    "localDealerCode" : "",
    "dealershipName" : "Peter Warren Ford",
    "addressLine1" : "Cnr Hume Hwy & Todman Avenue",
    "addressLine2" : null,
    "postcode" : "2170",
    "phoneNumber1" : "02-9828 8888",
    "phoneNumber2" : null,
    "fax" : "02-9828 8889",
    "website" : "www.peterwarrenford.com.au",
    "email" : "ebusiness@peterwarren.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Liverpool",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "67-000-293-621",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "21490#@##@#Peter Warren Ford",
    "latitudeLongitude" : {
        "latitude" : -33.911318,
        "longitude" : 150.938069,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "28120",
    "localDealerCode" : "",
    "dealershipName" : "Power Ford",
    "addressLine1" : "17 Victoria Avenue",
    "addressLine2" : null,
    "postcode" : "2154",
    "phoneNumber1" : "02-9680 4799",
    "phoneNumber2" : null,
    "fax" : "02-9899 2198",
    "website" : "www.powerford.com.au",
    "email" : "admin@powerford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Castle Hill",
    "state" : "NSW",
    "pma" : "E63",
    "abn" : "84-088-817-912",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "28120#@##@#Power Ford",
    "latitudeLongitude" : {
        "latitude" : -33.731608,
        "longitude" : 150.980711,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "24250",
    "localDealerCode" : "",
    "dealershipName" : "Robert Handsaker Ford",
    "addressLine1" : "14-18 Nymagee Street",
    "addressLine2" : null,
    "postcode" : "2821",
    "phoneNumber1" : "02-6889 1011",
    "phoneNumber2" : null,
    "fax" : "02-6889 2385",
    "website" : "",
    "email" : "newcars@roberthandsaker.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Narromine",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "29-003-680-519",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "24250#@##@#Robert Handsaker Ford",
    "latitudeLongitude" : {
        "latitude" : -32.232392,
        "longitude" : 148.238248,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "33440",
    "localDealerCode" : "",
    "dealershipName" : "Rural Ford",
    "addressLine1" : "45-57 Davidson Street",
    "addressLine2" : null,
    "postcode" : "2710",
    "phoneNumber1" : "03-5881 1233",
    "phoneNumber2" : null,
    "fax" : "03-5881 3969",
    "website" : "",
    "email" : "",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Deniliquin",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "78-258-819-632",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "33440#@##@#Rural Ford",
    "latitudeLongitude" : {
        "latitude" : -35.527436,
        "longitude" : 144.972134,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "21681",
    "localDealerCode" : "",
    "dealershipName" : "Sinclair Ford",
    "addressLine1" : "11 Sovereign Place",
    "addressLine2" : null,
    "postcode" : "2756",
    "phoneNumber1" : "02-4587 7111",
    "phoneNumber2" : null,
    "fax" : "TBA",
    "website" : "www.sinclairford.com.au",
    "email" : "servicewindsor@sinclairford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "South Windsor",
    "state" : "NSW",
    "pma" : "",
    "abn" : "72-112-718-420",
    "authorised" : "Parts, Service",
    "function" : "Parts & Service Branch",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "21681#@##@#Sinclair Ford",
    "latitudeLongitude" : {
        "latitude" : -33.618881,
        "longitude" : 150.81456,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "21680",
    "localDealerCode" : "",
    "dealershipName" : "Sinclair Ford",
    "addressLine1" : "117-120 Great Western Highway",
    "addressLine2" : null,
    "postcode" : "2747",
    "phoneNumber1" : "02-4721 4321",
    "phoneNumber2" : null,
    "fax" : "02-4721 8788",
    "website" : "www.sinclairford.com.au",
    "email" : "reception@sinclairford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Kingswood",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "72-112-718-420",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "21680#@##@#Sinclair Ford",
    "latitudeLongitude" : {
        "latitude" : -33.76041,
        "longitude" : 150.729584,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "22072",
    "localDealerCode" : "",
    "dealershipName" : "South Coast Ford",
    "addressLine1" : "27 Gregory Street",
    "addressLine2" : null,
    "postcode" : "2536",
    "phoneNumber1" : "02-4472 8888",
    "phoneNumber2" : null,
    "fax" : "02-4472 5275",
    "website" : "www.southcoastford.com.au",
    "email" : "service@southcoastford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Batemans Bay",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "95-128-147-473",
    "authorised" : "CPS Participating, Parts, Service",
    "function" : "Parts & Service Branch",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "22072#@##@#South Coast Ford",
    "latitudeLongitude" : {
        "latitude" : -35.718513,
        "longitude" : 150.179157,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "22070",
    "localDealerCode" : "",
    "dealershipName" : "South Coast Ford",
    "addressLine1" : "Cnr Beach Road & Orient Street",
    "addressLine2" : null,
    "postcode" : "2536",
    "phoneNumber1" : "02-4472 9999",
    "phoneNumber2" : null,
    "fax" : "02-4472 5725",
    "website" : "www.southcoastford.com.au",
    "email" : "sales@southcoastford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Batemans Bay",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "95-128-147-473",
    "authorised" : "CPS Participating, New Cars, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "22070#@##@#South Coast Ford",
    "latitudeLongitude" : {
        "latitude" : -35.70842,
        "longitude" : 150.177613,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "23510",
    "localDealerCode" : "",
    "dealershipName" : "South West Ford",
    "addressLine1" : "121 Hoskins Street",
    "addressLine2" : null,
    "postcode" : "2666",
    "phoneNumber1" : "02-6977 2144",
    "phoneNumber2" : null,
    "fax" : "02-6977 4007",
    "website" : "",
    "email" : "info@southwestford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Temora",
    "state" : "NSW",
    "pma" : "",
    "abn" : "154-663-206",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "23510#@##@#South West Ford",
    "latitudeLongitude" : {
        "latitude" : -34.444401,
        "longitude" : 147.533112,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "22030",
    "localDealerCode" : "",
    "dealershipName" : "Tarra Ford",
    "addressLine1" : "151 Auckland Street",
    "addressLine2" : null,
    "postcode" : "2550",
    "phoneNumber1" : "02-6492 1666",
    "phoneNumber2" : null,
    "fax" : "02-6492 3552",
    "website" : "www.tarraford.com.au",
    "email" : "john@tarraford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Bega",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "43 603 279 022",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "22030#@##@#Tarra Ford",
    "latitudeLongitude" : {
        "latitude" : -36.675565,
        "longitude" : 149.840045,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25210",
    "localDealerCode" : "",
    "dealershipName" : "Taylor Ford",
    "addressLine1" : "72 Barber St",
    "addressLine2" : null,
    "postcode" : "2380",
    "phoneNumber1" : "02-6742 2599",
    "phoneNumber2" : null,
    "fax" : "02-6742 3981",
    "website" : "",
    "email" : "",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Gunnedah",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "48-087-423-292",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25210#@##@#Taylor Ford",
    "latitudeLongitude" : {
        "latitude" : -30.977883,
        "longitude" : 150.249606,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "21600",
    "localDealerCode" : "",
    "dealershipName" : "Thomson Ford",
    "addressLine1" : "87 Church Street",
    "addressLine2" : null,
    "postcode" : "2150",
    "phoneNumber1" : "02-9635 7466",
    "phoneNumber2" : null,
    "fax" : "02-9633 4753",
    "website" : "www.thomsonford.com.au",
    "email" : "info@thomsonford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Parramatta",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "72-112-718-420",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "21600#@##@#Thomson Ford",
    "latitudeLongitude" : {
        "latitude" : -33.819829,
        "longitude" : 151.003929,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "28090",
    "localDealerCode" : "",
    "dealershipName" : "Titan Ford",
    "addressLine1" : "780 Pittwater Road",
    "addressLine2" : null,
    "postcode" : "2100",
    "phoneNumber1" : "02-9938 8400",
    "phoneNumber2" : null,
    "fax" : "02-9938 3621",
    "website" : "www.titan.com.au",
    "email" : "reception@titan.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Brookvale",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "84-088-817-912",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "28090#@##@#Titan Ford",
    "latitudeLongitude" : {
        "latitude" : -33.760056,
        "longitude" : 151.278763,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "23360",
    "localDealerCode" : "",
    "dealershipName" : "Tony Leahey Ford",
    "addressLine1" : "Cnr Bathurst Rd & Lone Pine Ave",
    "addressLine2" : null,
    "postcode" : "2800",
    "phoneNumber1" : "02-6393 7200",
    "phoneNumber2" : null,
    "fax" : "02-6393 7299",
    "website" : "www.tonyleahey.com.au",
    "email" : "sales@tonyleahey.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Orange",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "45-001-913-597",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "23360#@##@#Tony Leahey Ford",
    "latitudeLongitude" : {
        "latitude" : -33.298311,
        "longitude" : 149.119226,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "15371",
    "localDealerCode" : "",
    "dealershipName" : "Trevan Ford",
    "addressLine1" : "476 River Street",
    "addressLine2" : null,
    "postcode" : "2478",
    "phoneNumber1" : "02-6681 4499",
    "phoneNumber2" : null,
    "fax" : "02-6681 6493",
    "website" : "www.trevanford.com.au",
    "email" : "enquiries@trevanford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "West Ballina",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "66-150-852-458",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Full Branch of Lismore",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "15371#@##@#Trevan Ford",
    "latitudeLongitude" : {
        "latitude" : -28.865322,
        "longitude" : 153.54821,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "15370",
    "localDealerCode" : "",
    "dealershipName" : "Trevan Ford",
    "addressLine1" : "217-223 Keen Street",
    "addressLine2" : null,
    "postcode" : "2480",
    "phoneNumber1" : "02-6627 7999",
    "phoneNumber2" : null,
    "fax" : "02-6627 7952",
    "website" : "www.trevanford.com.au",
    "email" : "enquiries@trevanford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Lismore",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "66-150-852-458",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "15370#@##@#Trevan Ford",
    "latitudeLongitude" : {
        "latitude" : -28.812207,
        "longitude" : 153.27629,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "25420",
    "localDealerCode" : "",
    "dealershipName" : "Valley Motors (Gloucester)",
    "addressLine1" : "38-40 Denison Street",
    "addressLine2" : null,
    "postcode" : "2422",
    "phoneNumber1" : "02-6558 1105",
    "phoneNumber2" : null,
    "fax" : "02-6558 2348",
    "website" : "N/A",
    "email" : "accounts@vmgford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Gloucester",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "78-347-948-419",
    "authorised" : "CPS Participating, Parts, Service, Used Cars",
    "function" : "Parts & Service Dealer",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "25420#@##@#Valley Motors (Gloucester)",
    "latitudeLongitude" : {
        "latitude" : -32.006957,
        "longitude" : 151.959786,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "15471",
    "localDealerCode" : "",
    "dealershipName" : "Victory Ford",
    "addressLine1" : "210 Tweed Valley Way",
    "addressLine2" : null,
    "postcode" : "2484",
    "phoneNumber1" : "02-6670 2080",
    "phoneNumber2" : null,
    "fax" : "02-6670 2099",
    "website" : "www.victoryford.com.au",
    "email" : "admin@victoryford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Murwillumbah",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "74-120-565-773",
    "authorised" : "CPS Participating, Parts, Service",
    "function" : "Parts & Service Branch",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "15471#@##@#Victory Ford",
    "latitudeLongitude" : {
        "latitude" : -28.327402,
        "longitude" : 153.408869,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "15470",
    "localDealerCode" : "",
    "dealershipName" : "Victory Ford",
    "addressLine1" : "10-20 Minjungbal Drive",
    "addressLine2" : null,
    "postcode" : "2486",
    "phoneNumber1" : "07-5524 3555",
    "phoneNumber2" : null,
    "fax" : "07-5524 7772",
    "website" : "www.victoryford.com.au",
    "email" : "admin@victoryford.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "South Tweed Heads",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "74-120-565-773",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "15470#@##@#Victory Ford",
    "latitudeLongitude" : {
        "latitude" : -28.197616,
        "longitude" : 153.543721,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "22060",
    "localDealerCode" : "",
    "dealershipName" : "Village Ford",
    "addressLine1" : "77 Maybe Street",
    "addressLine2" : null,
    "postcode" : "2632",
    "phoneNumber1" : "02-6458 3522",
    "phoneNumber2" : null,
    "fax" : "02-6458 3773",
    "website" : "",
    "email" : "villageford@bigpond.com",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Bombala",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "54-000-174-050",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "22060#@##@#Village Ford",
    "latitudeLongitude" : {
        "latitude" : -36.909594,
        "longitude" : 149.242071,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "22550",
    "localDealerCode" : "",
    "dealershipName" : "Volcan Ford",
    "addressLine1" : "204 Corrimal Street",
    "addressLine2" : null,
    "postcode" : "2500",
    "phoneNumber1" : "02-4229 7777",
    "phoneNumber2" : null,
    "fax" : "02-4226 2943",
    "website" : "www.volcanford.com.au",
    "email" : "tim.koppel@southernclassiccars.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Wollongong",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "56-108-422-108",
    "authorised" : "CPS Participating, FPV Dealer, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "Y",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "22550#@##@#Volcan Ford",
    "latitudeLongitude" : {
        "latitude" : -34.432941,
        "longitude" : 150.897719,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
}, {
    "name" : null,
    "country" : null,
    "dealerCode" : "24820",
    "localDealerCode" : "",
    "dealershipName" : "Zannes Bros. Ford",
    "addressLine1" : "102 Balo Street",
    "addressLine2" : null,
    "postcode" : "2400",
    "phoneNumber1" : "02-6752 6666",
    "phoneNumber2" : null,
    "fax" : "02-6752 3687",
    "website" : "",
    "email" : "zannessales@bigpond.com",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Moree",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "64-870-090-238",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Main Site",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "24820#@##@#Zannes Bros. Ford",
    "latitudeLongitude" : {
        "latitude" : -29.464883,
        "longitude" : 149.841866,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
} ]
