[ {
    "name" : null,
    "country" : null,
    "dealerCode" : "34011",
    "localDealerCode" : "",
    "dealershipName" : "Blacklocks Ford",
    "addressLine1" : "Cnr. Kaitlers & Wagga Roads",
    "addressLine2" : null,
    "postcode" : "2641",
    "phoneNumber1" : "02-6049 5500",
    "phoneNumber2" : null,
    "fax" : "02-6040 4545",
    "website" : "",
    "email" : "sales@blacklocks.com.au",
    "pageId" : "",
    "award" : "",
    "articleId" : "",
    "city" : "Albury",
    "state" : "NSW",
    "pma" : "N/A",
    "abn" : "",
    "authorised" : "CPS Participating, New Cars, Parts, Service, Used Cars",
    "function" : "Full Branch",
    "salesDealerFlag" : "",
    "dealerOrder" : null,
    "cityOrder" : null,
    "fullXtimeParticipant" : "N",
    "consumerURL" : null,
    "mobileURL" : null,
    "dealerInfo" : "34011#@##@#Blacklocks Ford",
    "latitudeLongitude" : {
        "latitude" : -36.036691,
        "longitude" : 146.965886,
        "locationName" : null,
        "confidence" : null
    },
    "dealerCategory" : "",
    "salesBusinessHours" : { },
    "partsBusinessHours" : { },
    "serviceBusinessHours" : { }
} ]
