[
  {
    "name": "Courtney & Patterson Ford",
    "country": "Australia",
    "dealerCode": "31330",
    "localDealerCode": "31330",
    "dealershipName": "Courtney & Patterson Ford",
    "addressLine1": "Cnr Banksia & Dora Streets ",
    "addressLine2": null,
    "postcode": "3081",
    "phoneNumber1": "03-9287 1577",
    "phoneNumber2": null,
    "fax": "03-9287 1575",
    "website": "www.cpford.com.au",
    "email": "philh@cpford.com.au",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Heidelberg",
    "state": "VIC",
    "pma": null,
    "abn": "98-005-562-443",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "31330#@#31330#@#Courtney & Patterson Ford",
    "latitudeLongitude": {
      "latitude": -37.7599685,
      "longitude": 145.0715287,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "City Ford",
    "country": "Australia",
    "dealerCode": "36220",
    "localDealerCode": "36220",
    "dealershipName": "City Ford",
    "addressLine1": "734 Elizabeth Street ",
    "addressLine2": null,
    "postcode": "3000",
    "phoneNumber1": "03-9349 1277",
    "phoneNumber2": null,
    "fax": "03-9347 4635",
    "website": "www.city-ford.com.au",
    "email": "info@city-ford.com.au",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Melbourne",
    "state": "VIC",
    "pma": null,
    "abn": "82-150-739-567",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "36220#@#36220#@#City Ford",
    "latitudeLongitude": {
      "latitude": -37.8015068,
      "longitude": 144.9575522,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Brighton Ford",
    "country": "Australia",
    "dealerCode": "31280",
    "localDealerCode": "31280",
    "dealershipName": "Brighton Ford",
    "addressLine1": "61-63 Nepean Highway ",
    "addressLine2": null,
    "postcode": "3185",
    "phoneNumber1": "1300-996-172",
    "phoneNumber2": null,
    "fax": "03-9523-8456",
    "website": "",
    "email": "",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Elsternwick",
    "state": "VIC",
    "pma": null,
    "abn": "",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "31280#@#31280#@#Brighton Ford",
    "latitudeLongitude": {
      "latitude": -37.889987,
      "longitude": 145.00190800000001,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Strapp Ford",
    "country": "Australia",
    "dealerCode": "31160",
    "localDealerCode": "31160",
    "dealershipName": "Strapp Ford",
    "addressLine1": "45 Burwood Highway ",
    "addressLine2": null,
    "postcode": "3125",
    "phoneNumber1": "03-8831 5111",
    "phoneNumber2": null,
    "fax": "03-8831 5110",
    "website": "www.strappford.com.au",
    "email": "newcars@strappford.com.au",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Burwood",
    "state": "VIC",
    "pma": null,
    "abn": "97-787-945-360",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "31160#@#31160#@#Strapp Ford",
    "latitudeLongitude": {
      "latitude": -37.850113,
      "longitude": 145.097326,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Strapp Ford",
    "country": "Australia",
    "dealerCode": "31163",
    "localDealerCode": "31163",
    "dealershipName": "Strapp Ford",
    "addressLine1": "25 Evans Street ",
    "addressLine2": null,
    "postcode": "3125",
    "phoneNumber1": "03-8831 5100",
    "phoneNumber2": null,
    "fax": "03-8831 5195",
    "website": "www.strappford.com.au",
    "email": "newcars@strappford.com.au",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Burwood",
    "state": "VIC",
    "pma": null,
    "abn": "97-787-945-360",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "31163#@#31163#@#Strapp Ford",
    "latitudeLongitude": {
      "latitude": -37.853694299999994,
      "longitude": 145.1026019,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Bayford",
    "country": "Australia",
    "dealerCode": "31060",
    "localDealerCode": "31060",
    "dealershipName": "Bayford",
    "addressLine1": "1033-1061 Sydney Road ",
    "addressLine2": null,
    "postcode": "3058",
    "phoneNumber1": "03-9297 5000",
    "phoneNumber2": null,
    "fax": "03-9297 5166",
    "website": "www.bayford.com.au",
    "email": "bayford1033@bayford.com.au",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Coburg",
    "state": "VIC",
    "pma": null,
    "abn": "22-007-414-593",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "31060#@#31060#@#Bayford",
    "latitudeLongitude": {
      "latitude": -37.7224309,
      "longitude": 144.9634477,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Courtney & Patterson Ford",
    "country": "Australia",
    "dealerCode": "31331",
    "localDealerCode": "31331",
    "dealershipName": "Courtney & Patterson Ford",
    "addressLine1": "33-61 Bell Street ",
    "addressLine2": null,
    "postcode": "3081",
    "phoneNumber1": "03-9287 1611",
    "phoneNumber2": null,
    "fax": "03-9287 1610",
    "website": "www.cpford.com.au",
    "email": "",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "West Heidelberg",
    "state": "VIC",
    "pma": null,
    "abn": "",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "31331#@#31331#@#Courtney & Patterson Ford",
    "latitudeLongitude": {
      "latitude": -37.754177,
      "longitude": 145.0532735,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Bayford",
    "country": "Australia",
    "dealerCode": "31066",
    "localDealerCode": "31066",
    "dealershipName": "Bayford",
    "addressLine1": "475 Grimshaw Street ",
    "addressLine2": null,
    "postcode": "3083",
    "phoneNumber1": "03-9467 5533",
    "phoneNumber2": null,
    "fax": "03-9467 7980",
    "website": "www.bayford.com.au",
    "email": "",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Bundoora",
    "state": "VIC",
    "pma": null,
    "abn": "22-007-414-593",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "31066#@#31066#@#Bayford",
    "latitudeLongitude": {
      "latitude": -37.701321,
      "longitude": 145.070404,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Bayford",
    "country": "Australia",
    "dealerCode": "31064",
    "localDealerCode": "31064",
    "dealershipName": "Bayford",
    "addressLine1": "100 Cooper Street ",
    "addressLine2": null,
    "postcode": "3076",
    "phoneNumber1": "03-9401 8888",
    "phoneNumber2": null,
    "fax": "03-9401 8898",
    "website": "www.bayford.com.au",
    "email": "bayford1033@bayford.com.au",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Epping",
    "state": "VIC",
    "pma": null,
    "abn": "",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "31064#@#31064#@#Bayford",
    "latitudeLongitude": {
      "latitude": -37.650842,
      "longitude": 145.020147,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Bayford",
    "country": "Australia",
    "dealerCode": "31061",
    "localDealerCode": "31061",
    "dealershipName": "Bayford",
    "addressLine1": "1724 Sydney Road ",
    "addressLine2": null,
    "postcode": "3061",
    "phoneNumber1": "03-9241 3030",
    "phoneNumber2": null,
    "fax": "03-9241 3033",
    "website": "www.bayford.com.au",
    "email": "bayfordparts@bayford.com.au",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Campbellfield",
    "state": "VIC",
    "pma": null,
    "abn": "",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "31061#@#31061#@#Bayford",
    "latitudeLongitude": {
      "latitude": -37.673872,
      "longitude": 144.956678,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Essendon Ford",
    "country": "Australia",
    "dealerCode": "31430",
    "localDealerCode": "31430",
    "dealershipName": "Essendon Ford",
    "addressLine1": "330 Wirraway Road ",
    "addressLine2": null,
    "postcode": "3041",
    "phoneNumber1": "03-9374 7000",
    "phoneNumber2": null,
    "fax": "03-9374 7044",
    "website": "www.essendonford.com.au",
    "email": "jeffm@essendonford.com.au",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Essendon Fields",
    "state": "VIC",
    "pma": null,
    "abn": "96-564-774-759",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "31430#@#31430#@#Essendon Ford",
    "latitudeLongitude": {
      "latitude": -37.718049,
      "longitude": 144.895223,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Binks Ford",
    "country": "Australia",
    "dealerCode": "31412",
    "localDealerCode": "31412",
    "dealershipName": "Binks Ford",
    "addressLine1": "448 Geelong Road ",
    "addressLine2": null,
    "postcode": "3011",
    "phoneNumber1": "03-9687 5781",
    "phoneNumber2": null,
    "fax": "03-9689 2842",
    "website": "www.binks.com.au",
    "email": "info@binks.com.au",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Footscray",
    "state": "VIC",
    "pma": null,
    "abn": "33-689-943-810",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "31412#@#31412#@#Binks Ford",
    "latitudeLongitude": {
      "latitude": -37.798286899999994,
      "longitude": 144.8940042,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Westpoint Ford",
    "country": "Australia",
    "dealerCode": "32581",
    "localDealerCode": "32581",
    "dealershipName": "Westpoint Ford",
    "addressLine1": "758C Princes Highway ",
    "addressLine2": null,
    "postcode": "3026",
    "phoneNumber1": "03-9314 2988",
    "phoneNumber2": null,
    "fax": "03-9314 8688",
    "website": "www.westpointford.com.au",
    "email": "lavertonbookings@westpointford.com.au",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Laverton North",
    "state": "VIC",
    "pma": null,
    "abn": "52-063-570-856",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "32581#@#32581#@#Westpoint Ford",
    "latitudeLongitude": {
      "latitude": -37.8235798,
      "longitude": 144.824734,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Chadstone Ford",
    "country": "Australia",
    "dealerCode": "36490",
    "localDealerCode": "36490",
    "dealershipName": "Chadstone Ford",
    "addressLine1": "1406-1424 Dandenong Road ",
    "addressLine2": null,
    "postcode": "3166",
    "phoneNumber1": "03-9564 3777",
    "phoneNumber2": null,
    "fax": "03-9568 2240",
    "website": "www.chadstoneford.com.au",
    "email": "enquires@chadstoneford.com.au",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Oakleigh",
    "state": "VIC",
    "pma": null,
    "abn": "86-145-488-302",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "36490#@#36490#@#Chadstone Ford",
    "latitudeLongitude": {
      "latitude": -37.895781,
      "longitude": 145.098775,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Chadstone Ford",
    "country": "Australia",
    "dealerCode": "36492",
    "localDealerCode": "36492",
    "dealershipName": "Chadstone Ford",
    "addressLine1": "Units 3 & 4, 1 Garden Road ",
    "addressLine2": null,
    "postcode": "3168",
    "phoneNumber1": "03-9561 0155",
    "phoneNumber2": null,
    "fax": "03-9561 0181",
    "website": "www.newoakford.com.au",
    "email": "newoak@newoakford.com.au",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Clayton North",
    "state": "VIC",
    "pma": null,
    "abn": "86-145-488-302",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "36492#@#36492#@#Chadstone Ford",
    "latitudeLongitude": {
      "latitude": -37.9118548,
      "longitude": 145.1320653,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  },
  {
    "name": "Binks Ford",
    "country": "Australia",
    "dealerCode": "31410",
    "localDealerCode": "31410",
    "dealershipName": "Binks Ford",
    "addressLine1": "766 Ballarat Road ",
    "addressLine2": null,
    "postcode": "3023",
    "phoneNumber1": "03-8363 1555",
    "phoneNumber2": null,
    "fax": "03-8363 1566",
    "website": "www.binks.com.au",
    "email": "info@binks.com.au",
    "pageId": null,
    "award": null,
    "articleId": null,
    "city": "Deer Park",
    "state": "VIC",
    "pma": null,
    "abn": "33-689-943-810",
    "authorised": null,
    "function": null,
    "salesDealerFlag": null,
    "dealerOrder": null,
    "cityOrder": null,
    "fullXtimeParticipant": "N",
    "consumerURL": null,
    "mobileURL": null,
    "dealerInfo": "31410#@#31410#@#Binks Ford",
    "latitudeLongitude": {
      "latitude": -37.770154,
      "longitude": 144.78333500000002,
      "locationName": null,
      "confidence": null
    },
    "dealerCategory": null,
    "salesBusinessHours": {
      "Monday": "Closed",
      "Tuesday": "Closed",
      "Wednesday": "Closed",
      "Thursday": "Closed",
      "Friday": "Closed",
      "Saturday": "Closed",
      "Sunday": "Closed"
    },
    "partsBusinessHours": {},
    "serviceBusinessHours": {}
  }
]