[
  {
    "name": "4x4-xl-double-cc-2-2-diesel-Brisbane",
	"nameplateId": "1178856483523",
    "description": "",
    "selectTemplate": "/controller",
    "status": "Edited",
    "startDate": "",
    "endDate": "",
    "locale": "",
    "id": 1,
    "category": "General",
    "filename": "",
    "path": "",
    "nameplateName": "Ranger",
    "nameplateCKS": 57,
    "derivativeName": "4X4 XL Double Cab Chassis",
    "derivativeMarketingName": "4x4 XL Double CC 2.2 Diesel",
    "URIParameter": "4x4-xl-double-cc-2-2-diesel",
    "expiryDate": "Tuesday, July 1, 2200 12:00:00 PM EDT",
    "derivativeCKS": 57147,
    "derivativeAssetID": 1248851767025,
    "nameplate_modelID": 1178863971742,
    "priceDisclaimer": "Recommended offer price for 2012 plate manual vehicles at participating Dealers.",
    "blurbs": "Latest Ford Ranger 4x4 XL Double Cab Chassis deals from your participating Ford Dealer",
    "features": "2.2 turbo diesel engine 6 speed manual Towing Capacity of 3,500kg** 800mm Water Wading^^ BluetoothÂ® with Voice Control# iPod~ integration Cruise control Dynamic Stability Control with ABS Accessory trayÂ° Blue, Silver and Gold Business Fleet customers only",
    "logo1": "ANCAP - 5 star safety rating",
    "logo2": "Capped Price Service",
    "globalDisclaimer": "",
    "localDisclaimer": "* Limited offers available on 2012 plate new vehicles at participating Dealers. Blue, Silver and Gold Business Fleet customers only. Stock may vary between Dealers. All prices are recommended. Ford Dealers and Ford Australia reserve the right to change or extend these offers. #BluetoothÂ® is a registered trademark of Bluetooth SIG Inc., and is used under licence. Customers should consult their Ford Dealer on the ability of their mobile phone handset to integrate with the BluetoothÂ® system prior to making a purchase decision. ~iPod is a trademark of Apple Inc. Please refer to ford.com.au for iPod compatibility. ** Braked towing capacity when fitted with an optional towpack and towball. Subject to State and Territory regulations. ^^ Achieved when maintaining a steady speed of not more than 7km per hour. Â° This accessory is a Supplier Branded Accessory and is not manufactured or warranted by Ford. The warranty is provided by the manufacturer of the accessory. Â§myFord Capped Price Servicing available at participating Authorised Ford Dealers for Ford vehicles built from 2007 and up to 7 years or 105,000km, whichever comes first. Refer to Terms and Conditions at www.ford.com.au/myfordcps for full details.",
    "offerPrice": 10000,
    "offerRegion": "Brisbane (Brisbane)",
    "order": 0,
    "related": "No Related Assets",
    "image": "media/img1.jpg",
    "campaign": "Campaign 4|Campaign 1"
  },
  {
    "name": "Fiesta Ambiente",
	"nameplateId": "1178856483523",
    "description": "2.0L GDI petrol with 5-speed manual transmission",
    "selectTemplate": "/controller",
    "status": "Edited",
    "startDate": "",
    "endDate": "",
    "locale": "",
    "id": 2,
    "category": "General",
    "filename": "",
    "path": "",
    "nameplateName": "Ranger",
    "nameplateCKS": 57,
    "derivativeName": "4X4 XL Double Cab Chassis",
    "derivativeMarketingName": "4x4 XL Double CC 2.2 Diesel",
    "URIParameter": "4x4-xl-double-cc-2-2-diesel",
    "expiryDate": "Tuesday, July 1, 2200 12:00:00 PM EDT",
    "derivativeCKS": 57147,
    "derivativeAssetID": 1248851767025,
    "nameplate_modelID": 1178863971742,
    "priceDisclaimer": "Recommended offer price for 2012 plate manual vehicles at participating Dealers.",
    "blurbs": "Latest Ford Ranger 4x4 XL Double Cab Chassis deals from your participating Ford Dealer",
    "features": "2.2 turbo diesel engine 6 speed manual Towing Capacity of 3,500kg** 800mm Water Wading^^ BluetoothÂ® with Voice Control# iPod~ integration Cruise control Dynamic Stability Control with ABS Accessory trayÂ° Blue, Silver and Gold Business Fleet customers only",
    "logo1": "ANCAP - 5 star safety rating",
    "logo2": "Capped Price Service",
    "globalDisclaimer": "",
    "localDisclaimer": "* Limited offers available on 2012 plate new vehicles at participating Dealers. Blue, Silver and Gold Business Fleet customers only. Stock may vary between Dealers. All prices are recommended. Ford Dealers and Ford Australia reserve the right to change or extend these offers. #BluetoothÂ® is a registered trademark of Bluetooth SIG Inc., and is used under licence. Customers should consult their Ford Dealer on the ability of their mobile phone handset to integrate with the BluetoothÂ® system prior to making a purchase decision. ~iPod is a trademark of Apple Inc. Please refer to ford.com.au for iPod compatibility. ** Braked towing capacity when fitted with an optional towpack and towball. Subject to State and Territory regulations. ^^ Achieved when maintaining a steady speed of not more than 7km per hour. Â° This accessory is a Supplier Branded Accessory and is not manufactured or warranted by Ford. The warranty is provided by the manufacturer of the accessory. Â§myFord Capped Price Servicing available at participating Authorised Ford Dealers for Ford vehicles built from 2007 and up to 7 years or 105,000km, whichever comes first. Refer to Terms and Conditions at www.ford.com.au/myfordcps for full details.",
    "offerPrice": 11000,
    "offerRegion": "Brisbane (Brisbane)",
    "order": 0,
    "related": "No Related Assets",
    "image": "media/img1.jpg",
    "campaign": "Campaign 4"
  },
  {
    "name": "Territory TX RWD Petrol",
	"nameplateId": "1178856483523",
    "description": "4.0L DOHC DI-VCT I6 petrol engine (Standard)",
    "selectTemplate": "/controller",
    "status": "Edited",
    "startDate": "",
    "endDate": "",
    "locale": "",
    "id": 3,
    "category": "General",
    "filename": "",
    "path": "",
    "nameplateName": "Ranger",
    "nameplateCKS": 57,
    "derivativeName": "4X4 XL Double Cab Chassis",
    "derivativeMarketingName": "4x4 XL Double CC 2.2 Diesel",
    "URIParameter": "4x4-xl-double-cc-2-2-diesel",
    "expiryDate": "Tuesday, July 1, 2200 12:00:00 PM EDT",
    "derivativeCKS": 57147,
    "derivativeAssetID": 1248851767025,
    "nameplate_modelID": 1178863971742,
    "priceDisclaimer": "Recommended offer price for 2012 plate manual vehicles at participating Dealers.",
    "blurbs": "Latest Ford Ranger 4x4 XL Double Cab Chassis deals from your participating Ford Dealer",
    "features": "2.2 turbo diesel engine 6 speed manual Towing Capacity of 3,500kg** 800mm Water Wading^^ BluetoothÂ® with Voice Control# iPod~ integration Cruise control Dynamic Stability Control with ABS Accessory trayÂ° Blue, Silver and Gold Business Fleet customers only",
    "logo1": "ANCAP - 5 star safety rating",
    "logo2": "Capped Price Service",
    "globalDisclaimer": "",
    "localDisclaimer": "* Limited offers available on 2012 plate new vehicles at participating Dealers. Blue, Silver and Gold Business Fleet customers only. Stock may vary between Dealers. All prices are recommended. Ford Dealers and Ford Australia reserve the right to change or extend these offers. #BluetoothÂ® is a registered trademark of Bluetooth SIG Inc., and is used under licence. Customers should consult their Ford Dealer on the ability of their mobile phone handset to integrate with the BluetoothÂ® system prior to making a purchase decision. ~iPod is a trademark of Apple Inc. Please refer to ford.com.au for iPod compatibility. ** Braked towing capacity when fitted with an optional towpack and towball. Subject to State and Territory regulations. ^^ Achieved when maintaining a steady speed of not more than 7km per hour. Â° This accessory is a Supplier Branded Accessory and is not manufactured or warranted by Ford. The warranty is provided by the manufacturer of the accessory. Â§myFord Capped Price Servicing available at participating Authorised Ford Dealers for Ford vehicles built from 2007 and up to 7 years or 105,000km, whichever comes first. Refer to Terms and Conditions at www.ford.com.au/myfordcps for full details.",
    "offerPrice": 12000,
    "offerRegion": "Brisbane (Brisbane)",
    "order": 0,
    "related": "No Related Assets",
    "image": "media/img2.jpg",
    "campaign": "Campaign 3"
  },
  {
    "name": "Fiesta Ambiente",
	"nameplateId": "1178856483523",
    "description": "2.0L GDI petrol with 5-speed manual transmission",
    "selectTemplate": "/controller",
    "status": "Edited",
    "startDate": "",
    "endDate": "",
    "locale": "",
    "id": 4,
    "category": "General",
    "filename": "",
    "path": "",
    "nameplateName": "Ranger",
    "nameplateCKS": 57,
    "derivativeName": "4X4 XL Double Cab Chassis",
    "derivativeMarketingName": "4x4 XL Double CC 2.2 Diesel",
    "URIParameter": "4x4-xl-double-cc-2-2-diesel",
    "expiryDate": "Tuesday, July 1, 2200 12:00:00 PM EDT",
    "derivativeCKS": 57147,
    "derivativeAssetID": 1248851767025,
    "nameplate_modelID": 1178863971742,
    "priceDisclaimer": "Recommended offer price for 2012 plate manual vehicles at participating Dealers.",
    "blurbs": "Latest Ford Ranger 4x4 XL Double Cab Chassis deals from your participating Ford Dealer",
    "features": "2.2 turbo diesel engine 6 speed manual Towing Capacity of 3,500kg** 800mm Water Wading^^ BluetoothÂ® with Voice Control# iPod~ integration Cruise control Dynamic Stability Control with ABS Accessory trayÂ° Blue, Silver and Gold Business Fleet customers only",
    "logo1": "ANCAP - 5 star safety rating",
    "logo2": "Capped Price Service",
    "globalDisclaimer": "",
    "localDisclaimer": "* Limited offers available on 2012 plate new vehicles at participating Dealers. Blue, Silver and Gold Business Fleet customers only. Stock may vary between Dealers. All prices are recommended. Ford Dealers and Ford Australia reserve the right to change or extend these offers. #BluetoothÂ® is a registered trademark of Bluetooth SIG Inc., and is used under licence. Customers should consult their Ford Dealer on the ability of their mobile phone handset to integrate with the BluetoothÂ® system prior to making a purchase decision. ~iPod is a trademark of Apple Inc. Please refer to ford.com.au for iPod compatibility. ** Braked towing capacity when fitted with an optional towpack and towball. Subject to State and Territory regulations. ^^ Achieved when maintaining a steady speed of not more than 7km per hour. Â° This accessory is a Supplier Branded Accessory and is not manufactured or warranted by Ford. The warranty is provided by the manufacturer of the accessory. Â§myFord Capped Price Servicing available at participating Authorised Ford Dealers for Ford vehicles built from 2007 and up to 7 years or 105,000km, whichever comes first. Refer to Terms and Conditions at www.ford.com.au/myfordcps for full details.",
    "offerPrice": 30000,
    "offerRegion": "Brisbane (Brisbane)",
    "order": 0,
    "related": "No Related Assets",
    "image": "media/img3.jpg",
    "campaign": "Campaign 3|Campaign 4"
  },
  {
    "name": "Fiesta Ambiente",
	"nameplateId": "1178856483523",
    "description": "2.0L GDI petrol with 5-speed manual transmission",
    "selectTemplate": "/controller",
    "status": "Edited",
    "startDate": "",
    "endDate": "",
    "locale": "",
    "id": 5,
    "category": "General",
    "filename": "",
    "path": "",
    "nameplateName": "Ranger",
    "nameplateCKS": 57,
    "derivativeName": "4X4 XL Double Cab Chassis",
    "derivativeMarketingName": "4x4 XL Double CC 2.2 Diesel",
    "URIParameter": "4x4-xl-double-cc-2-2-diesel",
    "expiryDate": "Tuesday, July 1, 2200 12:00:00 PM EDT",
    "derivativeCKS": 57147,
    "derivativeAssetID": 1248851767025,
    "nameplate_modelID": 1178863971742,
    "priceDisclaimer": "Recommended offer price for 2012 plate manual vehicles at participating Dealers.",
    "blurbs": "Latest Ford Ranger 4x4 XL Double Cab Chassis deals from your participating Ford Dealer",
    "features": "2.2 turbo diesel engine 6 speed manual Towing Capacity of 3,500kg** 800mm Water Wading^^ BluetoothÂ® with Voice Control# iPod~ integration Cruise control Dynamic Stability Control with ABS Accessory trayÂ° Blue, Silver and Gold Business Fleet customers only",
    "logo1": "ANCAP - 5 star safety rating",
    "logo2": "Capped Price Service",
    "globalDisclaimer": "",
    "localDisclaimer": "* Limited offers available on 2012 plate new vehicles at participating Dealers. Blue, Silver and Gold Business Fleet customers only. Stock may vary between Dealers. All prices are recommended. Ford Dealers and Ford Australia reserve the right to change or extend these offers. #BluetoothÂ® is a registered trademark of Bluetooth SIG Inc., and is used under licence. Customers should consult their Ford Dealer on the ability of their mobile phone handset to integrate with the BluetoothÂ® system prior to making a purchase decision. ~iPod is a trademark of Apple Inc. Please refer to ford.com.au for iPod compatibility. ** Braked towing capacity when fitted with an optional towpack and towball. Subject to State and Territory regulations. ^^ Achieved when maintaining a steady speed of not more than 7km per hour. Â° This accessory is a Supplier Branded Accessory and is not manufactured or warranted by Ford. The warranty is provided by the manufacturer of the accessory. Â§myFord Capped Price Servicing available at participating Authorised Ford Dealers for Ford vehicles built from 2007 and up to 7 years or 105,000km, whichever comes first. Refer to Terms and Conditions at www.ford.com.au/myfordcps for full details.",
    "offerPrice": 35000,
    "offerRegion": "Brisbane (Brisbane)",
    "order": 0,
    "related": "No Related Assets",
    "image": "media/img4.jpg",
    "campaign": "Campaign 2|Campaign 4"
  },
  {
    "name": "Fiesta Ambiente",
	"nameplateId": "1178856483523",
    "description": "2.0L GDI petrol with 5-speed manual transmission",
    "selectTemplate": "/controller",
    "status": "Edited",
    "startDate": "",
    "endDate": "",
    "locale": "",
    "id": 6,
    "category": "General",
    "filename": "",
    "path": "",
    "nameplateName": "Ranger",
    "nameplateCKS": 57,
    "derivativeName": "4X4 XL Double Cab Chassis",
    "derivativeMarketingName": "4x4 XL Double CC 2.2 Diesel",
    "URIParameter": "4x4-xl-double-cc-2-2-diesel",
    "expiryDate": "Tuesday, July 1, 2200 12:00:00 PM EDT",
    "derivativeCKS": 57147,
    "derivativeAssetID": 1248851767025,
    "nameplate_modelID": 1178863971742,
    "priceDisclaimer": "Recommended offer price for 2012 plate manual vehicles at participating Dealers.",
    "blurbs": "Latest Ford Ranger 4x4 XL Double Cab Chassis deals from your participating Ford Dealer",
    "features": "2.2 turbo diesel engine 6 speed manual Towing Capacity of 3,500kg** 800mm Water Wading^^ BluetoothÂ® with Voice Control# iPod~ integration Cruise control Dynamic Stability Control with ABS Accessory trayÂ° Blue, Silver and Gold Business Fleet customers only",
    "logo1": "ANCAP - 5 star safety rating",
    "logo2": "Capped Price Service",
    "globalDisclaimer": "",
    "localDisclaimer": "* Limited offers available on 2012 plate new vehicles at participating Dealers. Blue, Silver and Gold Business Fleet customers only. Stock may vary between Dealers. All prices are recommended. Ford Dealers and Ford Australia reserve the right to change or extend these offers. #BluetoothÂ® is a registered trademark of Bluetooth SIG Inc., and is used under licence. Customers should consult their Ford Dealer on the ability of their mobile phone handset to integrate with the BluetoothÂ® system prior to making a purchase decision. ~iPod is a trademark of Apple Inc. Please refer to ford.com.au for iPod compatibility. ** Braked towing capacity when fitted with an optional towpack and towball. Subject to State and Territory regulations. ^^ Achieved when maintaining a steady speed of not more than 7km per hour. Â° This accessory is a Supplier Branded Accessory and is not manufactured or warranted by Ford. The warranty is provided by the manufacturer of the accessory. Â§myFord Capped Price Servicing available at participating Authorised Ford Dealers for Ford vehicles built from 2007 and up to 7 years or 105,000km, whichever comes first. Refer to Terms and Conditions at www.ford.com.au/myfordcps for full details.",
    "offerPrice": 60000,
    "offerRegion": "Brisbane (Brisbane)",
    "order": 0,
    "related": "No Related Assets",
    "image": "media/img5.jpg",
    "campaign": "campaign1"
  },
  {
    "name": "Fiesta Ambiente",
	"nameplateId": "1178856483523",
    "description": "2.0L GDI petrol with 5-speed manual transmission",
    "selectTemplate": "/controller",
    "status": "Edited",
    "startDate": "",
    "endDate": "",
    "locale": "",
    "id": 7,
    "category": "General",
    "filename": "",
    "path": "",
    "nameplateName": "Ranger",
    "nameplateCKS": 57,
    "derivativeName": "4X4 XL Double Cab Chassis",
    "derivativeMarketingName": "4x4 XL Double CC 2.2 Diesel",
    "URIParameter": "4x4-xl-double-cc-2-2-diesel",
    "expiryDate": "Tuesday, July 1, 2200 12:00:00 PM EDT",
    "derivativeCKS": 57147,
    "derivativeAssetID": 1248851767025,
    "nameplate_modelID": 1178863971742,
    "priceDisclaimer": "Recommended offer price for 2012 plate manual vehicles at participating Dealers.",
    "blurbs": "Latest Ford Ranger 4x4 XL Double Cab Chassis deals from your participating Ford Dealer",
    "features": "2.2 turbo diesel engine 6 speed manual Towing Capacity of 3,500kg** 800mm Water Wading^^ BluetoothÂ® with Voice Control# iPod~ integration Cruise control Dynamic Stability Control with ABS Accessory trayÂ° Blue, Silver and Gold Business Fleet customers only",
    "logo1": "ANCAP - 5 star safety rating",
    "logo2": "Capped Price Service",
    "globalDisclaimer": "",
    "localDisclaimer": "* Limited offers available on 2012 plate new vehicles at participating Dealers. Blue, Silver and Gold Business Fleet customers only. Stock may vary between Dealers. All prices are recommended. Ford Dealers and Ford Australia reserve the right to change or extend these offers. #BluetoothÂ® is a registered trademark of Bluetooth SIG Inc., and is used under licence. Customers should consult their Ford Dealer on the ability of their mobile phone handset to integrate with the BluetoothÂ® system prior to making a purchase decision. ~iPod is a trademark of Apple Inc. Please refer to ford.com.au for iPod compatibility. ** Braked towing capacity when fitted with an optional towpack and towball. Subject to State and Territory regulations. ^^ Achieved when maintaining a steady speed of not more than 7km per hour. Â° This accessory is a Supplier Branded Accessory and is not manufactured or warranted by Ford. The warranty is provided by the manufacturer of the accessory. Â§myFord Capped Price Servicing available at participating Authorised Ford Dealers for Ford vehicles built from 2007 and up to 7 years or 105,000km, whichever comes first. Refer to Terms and Conditions at www.ford.com.au/myfordcps for full details.",
    "offerPrice": 55000,
    "offerRegion": "Brisbane (Brisbane)",
    "order": 0,
    "related": "No Related Assets",
    "image": "media/img6.jpg",
    "campaign": "campaign2"
  },
  {
    "name": "Fiesta Ambiente",
	"nameplateId": "1178856483523",
    "description": "2.0L GDI petrol with 5-speed manual transmission",
    "selectTemplate": "/controller",
    "status": "Edited",
    "startDate": "",
    "endDate": "",
    "locale": "",
    "id": 8,
    "category": "General",
    "filename": "",
    "path": "",
    "nameplateName": "Ranger",
    "nameplateCKS": 57,
    "derivativeName": "4X4 XL Double Cab Chassis",
    "derivativeMarketingName": "4x4 XL Double CC 2.2 Diesel",
    "URIParameter": "4x4-xl-double-cc-2-2-diesel",
    "expiryDate": "Tuesday, July 1, 2200 12:00:00 PM EDT",
    "derivativeCKS": 57147,
    "derivativeAssetID": 1248851767025,
    "nameplate_modelID": 1178863971742,
    "priceDisclaimer": "Recommended offer price for 2012 plate manual vehicles at participating Dealers.",
    "blurbs": "Latest Ford Ranger 4x4 XL Double Cab Chassis deals from your participating Ford Dealer",
    "features": "2.2 turbo diesel engine 6 speed manual Towing Capacity of 3,500kg** 800mm Water Wading^^ BluetoothÂ® with Voice Control# iPod~ integration Cruise control Dynamic Stability Control with ABS Accessory trayÂ° Blue, Silver and Gold Business Fleet customers only",
    "logo1": "ANCAP - 5 star safety rating",
    "logo2": "Capped Price Service",
    "globalDisclaimer": "",
    "localDisclaimer": "* Limited offers available on 2012 plate new vehicles at participating Dealers. Blue, Silver and Gold Business Fleet customers only. Stock may vary between Dealers. All prices are recommended. Ford Dealers and Ford Australia reserve the right to change or extend these offers. #BluetoothÂ® is a registered trademark of Bluetooth SIG Inc., and is used under licence. Customers should consult their Ford Dealer on the ability of their mobile phone handset to integrate with the BluetoothÂ® system prior to making a purchase decision. ~iPod is a trademark of Apple Inc. Please refer to ford.com.au for iPod compatibility. ** Braked towing capacity when fitted with an optional towpack and towball. Subject to State and Territory regulations. ^^ Achieved when maintaining a steady speed of not more than 7km per hour. Â° This accessory is a Supplier Branded Accessory and is not manufactured or warranted by Ford. The warranty is provided by the manufacturer of the accessory. Â§myFord Capped Price Servicing available at participating Authorised Ford Dealers for Ford vehicles built from 2007 and up to 7 years or 105,000km, whichever comes first. Refer to Terms and Conditions at www.ford.com.au/myfordcps for full details.",
    "offerPrice": 16000,
    "offerRegion": "Brisbane (Brisbane)",
    "order": 0,
    "related": "No Related Assets",
    "image": "media/img1.jpg",
    "campaign": "campaign3"
  },
  {
    "name": "Territory TX RWD Petrol",
	"nameplateId": "1178856483893",
    "description": "4.0L DOHC DI-VCT I6 petrol engine (Standard)",
    "selectTemplate": "/controller",
    "status": "Edited",
    "startDate": "",
    "endDate": "",
    "locale": "",
    "id": 9,
    "category": "General",
    "filename": "",
    "path": "",
    "nameplateName": "Ranger",
    "nameplateCKS": 57,
    "derivativeName": "4X4 XL Double Cab Chassis",
    "derivativeMarketingName": "4x4 XL Double CC 2.2 Diesel",
    "URIParameter": "4x4-xl-double-cc-2-2-diesel",
    "expiryDate": "Tuesday, July 1, 2200 12:00:00 PM EDT",
    "derivativeCKS": 57147,
    "derivativeAssetID": 1248851767025,
    "nameplate_modelID": 1178863971742,
    "priceDisclaimer": "Recommended offer price for 2012 plate manual vehicles at participating Dealers.",
    "blurbs": "Latest Ford Ranger 4x4 XL Double Cab Chassis deals from your participating Ford Dealer",
    "features": "2.2 turbo diesel engine 6 speed manual Towing Capacity of 3,500kg** 800mm Water Wading^^ BluetoothÂ® with Voice Control# iPod~ integration Cruise control Dynamic Stability Control with ABS Accessory trayÂ° Blue, Silver and Gold Business Fleet customers only",
    "logo1": "ANCAP - 5 star safety rating",
    "logo2": "Capped Price Service",
    "globalDisclaimer": "",
    "localDisclaimer": "* Limited offers available on 2012 plate new vehicles at participating Dealers. Blue, Silver and Gold Business Fleet customers only. Stock may vary between Dealers. All prices are recommended. Ford Dealers and Ford Australia reserve the right to change or extend these offers. #BluetoothÂ® is a registered trademark of Bluetooth SIG Inc., and is used under licence. Customers should consult their Ford Dealer on the ability of their mobile phone handset to integrate with the BluetoothÂ® system prior to making a purchase decision. ~iPod is a trademark of Apple Inc. Please refer to ford.com.au for iPod compatibility. ** Braked towing capacity when fitted with an optional towpack and towball. Subject to State and Territory regulations. ^^ Achieved when maintaining a steady speed of not more than 7km per hour. Â° This accessory is a Supplier Branded Accessory and is not manufactured or warranted by Ford. The warranty is provided by the manufacturer of the accessory. Â§myFord Capped Price Servicing available at participating Authorised Ford Dealers for Ford vehicles built from 2007 and up to 7 years or 105,000km, whichever comes first. Refer to Terms and Conditions at www.ford.com.au/myfordcps for full details.",
    "offerPrice": 19000,
    "offerRegion": "Brisbane (Brisbane)",
    "order": 0,
    "related": "No Related Assets",
    "image": "media/img2.jpg",
    "campaign": "campaign4"
  },
  {
    "name": "Fiesta Ambiente",
	"nameplateId": "1178856483524",
    "description": "2.0L GDI petrol with 5-speed manual transmission",
    "selectTemplate": "/controller",
    "status": "Edited",
    "startDate": "",
    "endDate": "",
    "locale": "",
    "id": 10,
    "category": "General",
    "filename": "",
    "path": "",
    "nameplateName": "Ranger",
    "nameplateCKS": 57,
    "derivativeName": "4X4 XL Double Cab Chassis",
    "derivativeMarketingName": "4x4 XL Double CC 2.2 Diesel",
    "URIParameter": "4x4-xl-double-cc-2-2-diesel",
    "expiryDate": "Tuesday, July 1, 2200 12:00:00 PM EDT",
    "derivativeCKS": 57147,
    "derivativeAssetID": 1248851767025,
    "nameplate_modelID": 1178863971742,
    "priceDisclaimer": "Recommended offer price for 2012 plate manual vehicles at participating Dealers.",
    "blurbs": "Latest Ford Ranger 4x4 XL Double Cab Chassis deals from your participating Ford Dealer",
    "features": "2.2 turbo diesel engine 6 speed manual Towing Capacity of 3,500kg** 800mm Water Wading^^ BluetoothÂ® with Voice Control# iPod~ integration Cruise control Dynamic Stability Control with ABS Accessory trayÂ° Blue, Silver and Gold Business Fleet customers only",
    "logo1": "ANCAP - 5 star safety rating",
    "logo2": "Capped Price Service",
    "globalDisclaimer": "",
    "localDisclaimer": "* Limited offers available on 2012 plate new vehicles at participating Dealers. Blue, Silver and Gold Business Fleet customers only. Stock may vary between Dealers. All prices are recommended. Ford Dealers and Ford Australia reserve the right to change or extend these offers. #BluetoothÂ® is a registered trademark of Bluetooth SIG Inc., and is used under licence. Customers should consult their Ford Dealer on the ability of their mobile phone handset to integrate with the BluetoothÂ® system prior to making a purchase decision. ~iPod is a trademark of Apple Inc. Please refer to ford.com.au for iPod compatibility. ** Braked towing capacity when fitted with an optional towpack and towball. Subject to State and Territory regulations. ^^ Achieved when maintaining a steady speed of not more than 7km per hour. Â° This accessory is a Supplier Branded Accessory and is not manufactured or warranted by Ford. The warranty is provided by the manufacturer of the accessory. Â§myFord Capped Price Servicing available at participating Authorised Ford Dealers for Ford vehicles built from 2007 and up to 7 years or 105,000km, whichever comes first. Refer to Terms and Conditions at www.ford.com.au/myfordcps for full details.",
    "offerPrice": 23000,
    "offerRegion": "Brisbane (Brisbane)",
    "order": 0,
    "related": "No Related Assets",
    "image": "media/img3.jpg",
    "campaign": "campaign2"
  },
  {
    "name": "Fiesta Ambiente",
	"nameplateId": "1178856483525",
    "description": "2.0L GDI petrol with 5-speed manual transmission",
    "selectTemplate": "/controller",
    "status": "Edited",
    "startDate": "",
    "endDate": "",
    "locale": "",
    "id": 11,
    "category": "General",
    "filename": "",
    "path": "",
    "nameplateName": "Ranger",
    "nameplateCKS": 57,
    "derivativeName": "4X4 XL Double Cab Chassis",
    "derivativeMarketingName": "4x4 XL Double CC 2.2 Diesel",
    "URIParameter": "4x4-xl-double-cc-2-2-diesel",
    "expiryDate": "Tuesday, July 1, 2200 12:00:00 PM EDT",
    "derivativeCKS": 57147,
    "derivativeAssetID": 1248851767025,
    "nameplate_modelID": 1178863971742,
    "priceDisclaimer": "Recommended offer price for 2012 plate manual vehicles at participating Dealers.",
    "blurbs": "Latest Ford Ranger 4x4 XL Double Cab Chassis deals from your participating Ford Dealer",
    "features": "2.2 turbo diesel engine 6 speed manual Towing Capacity of 3,500kg** 800mm Water Wading^^ BluetoothÂ® with Voice Control# iPod~ integration Cruise control Dynamic Stability Control with ABS Accessory trayÂ° Blue, Silver and Gold Business Fleet customers only",
    "logo1": "ANCAP - 5 star safety rating",
    "logo2": "Capped Price Service",
    "globalDisclaimer": "",
    "localDisclaimer": "* Limited offers available on 2012 plate new vehicles at participating Dealers. Blue, Silver and Gold Business Fleet customers only. Stock may vary between Dealers. All prices are recommended. Ford Dealers and Ford Australia reserve the right to change or extend these offers. #BluetoothÂ® is a registered trademark of Bluetooth SIG Inc., and is used under licence. Customers should consult their Ford Dealer on the ability of their mobile phone handset to integrate with the BluetoothÂ® system prior to making a purchase decision. ~iPod is a trademark of Apple Inc. Please refer to ford.com.au for iPod compatibility. ** Braked towing capacity when fitted with an optional towpack and towball. Subject to State and Territory regulations. ^^ Achieved when maintaining a steady speed of not more than 7km per hour. Â° This accessory is a Supplier Branded Accessory and is not manufactured or warranted by Ford. The warranty is provided by the manufacturer of the accessory. Â§myFord Capped Price Servicing available at participating Authorised Ford Dealers for Ford vehicles built from 2007 and up to 7 years or 105,000km, whichever comes first. Refer to Terms and Conditions at www.ford.com.au/myfordcps for full details.",
    "offerPrice": 44000,
    "offerRegion": "Brisbane (Brisbane)",
    "order": 0,
    "related": "No Related Assets",
    "image": "media/img4.jpg",
    "campaign": "campaign3"
  },
  {
    "name": "Fiesta Ambiente",
	"nameplateId": "1178856483526",
    "description": "2.0L GDI petrol with 5-speed manual transmission",
    "selectTemplate": "/controller",
    "status": "Edited",
    "startDate": "",
    "endDate": "",
    "locale": "",
    "id": 12,
    "category": "General",
    "filename": "",
    "path": "",
    "nameplateName": "Ranger",
    "nameplateCKS": 57,
    "derivativeName": "4X4 XL Double Cab Chassis",
    "derivativeMarketingName": "4x4 XL Double CC 2.2 Diesel",
    "URIParameter": "4x4-xl-double-cc-2-2-diesel",
    "expiryDate": "Tuesday, July 1, 2200 12:00:00 PM EDT",
    "derivativeCKS": 57147,
    "derivativeAssetID": 1248851767025,
    "nameplate_modelID": 1178863971742,
    "priceDisclaimer": "Recommended offer price for 2012 plate manual vehicles at participating Dealers.",
    "blurbs": "Latest Ford Ranger 4x4 XL Double Cab Chassis deals from your participating Ford Dealer",
    "features": "2.2 turbo diesel engine 6 speed manual Towing Capacity of 3,500kg** 800mm Water Wading^^ BluetoothÂ® with Voice Control# iPod~ integration Cruise control Dynamic Stability Control with ABS Accessory trayÂ° Blue, Silver and Gold Business Fleet customers only",
    "logo1": "ANCAP - 5 star safety rating",
    "logo2": "Capped Price Service",
    "globalDisclaimer": "",
    "localDisclaimer": "* Limited offers available on 2012 plate new vehicles at participating Dealers. Blue, Silver and Gold Business Fleet customers only. Stock may vary between Dealers. All prices are recommended. Ford Dealers and Ford Australia reserve the right to change or extend these offers. #BluetoothÂ® is a registered trademark of Bluetooth SIG Inc., and is used under licence. Customers should consult their Ford Dealer on the ability of their mobile phone handset to integrate with the BluetoothÂ® system prior to making a purchase decision. ~iPod is a trademark of Apple Inc. Please refer to ford.com.au for iPod compatibility. ** Braked towing capacity when fitted with an optional towpack and towball. Subject to State and Territory regulations. ^^ Achieved when maintaining a steady speed of not more than 7km per hour. Â° This accessory is a Supplier Branded Accessory and is not manufactured or warranted by Ford. The warranty is provided by the manufacturer of the accessory. Â§myFord Capped Price Servicing available at participating Authorised Ford Dealers for Ford vehicles built from 2007 and up to 7 years or 105,000km, whichever comes first. Refer to Terms and Conditions at www.ford.com.au/myfordcps for full details.",
    "offerPrice": 28000,
    "offerRegion": "Brisbane (Brisbane)",
    "order": 0,
    "related": "No Related Assets",
    "image": "media/img5.jpg",
    "campaign": "campaign3"
  },
  {
    "name": "Fiesta Ambiente",
	"nameplateId": "1178856483527",
    "description": "2.0L GDI petrol with 5-speed manual transmission",
    "selectTemplate": "/controller",
    "status": "Edited",
    "startDate": "",
    "endDate": "",
    "locale": "",
    "id": 13,
    "category": "General",
    "filename": "",
    "path": "",
    "nameplateName": "Ranger",
    "nameplateCKS": 57,
    "derivativeName": "4X4 XL Double Cab Chassis",
    "derivativeMarketingName": "4x4 XL Double CC 2.2 Diesel",
    "URIParameter": "4x4-xl-double-cc-2-2-diesel",
    "expiryDate": "Tuesday, July 1, 2200 12:00:00 PM EDT",
    "derivativeCKS": 57147,
    "derivativeAssetID": 1248851767025,
    "nameplate_modelID": 1178863971742,
    "priceDisclaimer": "Recommended offer price for 2012 plate manual vehicles at participating Dealers.",
    "blurbs": "Latest Ford Ranger 4x4 XL Double Cab Chassis deals from your participating Ford Dealer",
    "features": "2.2 turbo diesel engine 6 speed manual Towing Capacity of 3,500kg** 800mm Water Wading^^ BluetoothÂ® with Voice Control# iPod~ integration Cruise control Dynamic Stability Control with ABS Accessory trayÂ° Blue, Silver and Gold Business Fleet customers only",
    "logo1": "ANCAP - 5 star safety rating",
    "logo2": "Capped Price Service",
    "globalDisclaimer": "",
    "localDisclaimer": "* Limited offers available on 2012 plate new vehicles at participating Dealers. Blue, Silver and Gold Business Fleet customers only. Stock may vary between Dealers. All prices are recommended. Ford Dealers and Ford Australia reserve the right to change or extend these offers. #BluetoothÂ® is a registered trademark of Bluetooth SIG Inc., and is used under licence. Customers should consult their Ford Dealer on the ability of their mobile phone handset to integrate with the BluetoothÂ® system prior to making a purchase decision. ~iPod is a trademark of Apple Inc. Please refer to ford.com.au for iPod compatibility. ** Braked towing capacity when fitted with an optional towpack and towball. Subject to State and Territory regulations. ^^ Achieved when maintaining a steady speed of not more than 7km per hour. Â° This accessory is a Supplier Branded Accessory and is not manufactured or warranted by Ford. The warranty is provided by the manufacturer of the accessory. Â§myFord Capped Price Servicing available at participating Authorised Ford Dealers for Ford vehicles built from 2007 and up to 7 years or 105,000km, whichever comes first. Refer to Terms and Conditions at www.ford.com.au/myfordcps for full details.",
    "offerPrice": 20,
    "offerRegion": "Brisbane (Brisbane)",
    "order": 0,
    "related": "No Related Assets",
    "image": "media/img6.jpg",
    "campaign": "campaign1"
  }
]