{
  "HotDeals": [
    {
      "order": 1,
      "id": "1248854804447",
      "uriparameter": "fiesta-ambiente-1",
      "nameplatename": "fiesta",
      "nameplatecks": "17",
      "nameplateId": "1249113492342",
      "derivativeId": "1178856483571",
      "derivativename": "Fiesta Ambiente 1",
      "derivativemarketingname": "Fiesta Ambiente 1",
      "derivativecks": "17353",
      "pricedisclaimer": "Recommended offer … ",
      "blurbs": "Latest Ford Fiesta Ambiente deals from your participating Ford Dealer",
      "features": "Fuel efficient 1…",
      "logo1": "ancap",
      "logo2": "Ecoboost",
      "logo3": "Power",
      "differentiatorlabel1": "ANCAP",
      "differentiatorlabel2": "Ecoboost",
      "differentiatorlabel3": "134 kW power",
      "localdisclaimer": "* Limited offers ...",
      "offerprice": "13000.0",
      "offerregion": "National",
      "campaigns": [],
      "category": "g",
      "status": "PL",
      "createdby": "fxiong",
      "createddate": "2013-10-31 14:55:47.0 EST",
      "updatedby": "fxiong",
      "updateddate": "2013-11-05 19:37:53.767 EST",
      "name": "fiesta-ambiente-1-National",
      "template": "/controller",
      "expiryDate": "2100-11-01 12:00:00.0 EST",
      "indexImage": "1248850583594",
      "indexImageMainUrl": "media/img6.jpg",
      "indexImageThumbnailUrl": "media/img9.png",
      "smobIndexImage": "1248854071385",
      "smobIndexImageMainUrl": "media/img7.jpg",
      "smobIndexImageThumbnailUrl": "/servlet/Satellite?blobtable=…",
      "heroImage": "1248851233062",
      "heroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "heroImageThumbnailUrl": "",
      "smobHeroImage": "1248854071799",
      "smobHeroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "smobHeroImageThumbnailUrl": "",
      "hotDealUrl": "/hot-deals-test/national/fiesta?sitetype=web ",
      "hotDealSmobUrl": "/smob/hot-deals-test/national/fiesta?sitetype=…"
    },
	{
      "order": 12,
      "id": "1248854804448",
      "uriparameter": "fiesta-ambiente-1",
      "nameplatename": "fiesta",
      "nameplatecks": "17",
      "nameplateId": "1249113492342",
      "derivativeId": "1178856483571",
      "derivativename": "Fiesta Ambiente 1",
      "derivativemarketingname": "Fiesta Ambiente 1",
      "derivativecks": "17353",
      "pricedisclaimer": "Recommended offer … ",
      "blurbs": "Latest Ford Fiesta Ambiente deals from your participating Ford Dealer",
      "features": "Fuel efficient 1…",
      "logo1": "ancap",
      "logo2": "Ecoboost",
      "logo3": "Power",
      "differentiatorlabel1": "ANCAP",
      "differentiatorlabel2": "Ecoboost",
      "differentiatorlabel3": "134 kW power",
      "localdisclaimer": "* Limited offers ...",
      "offerprice": "12000.0",
      "offerregion": "National",
      "campaigns": [
        "campaign2",
        "campaign3"
      ],
      "category": "g",
      "status": "PL",
      "createdby": "fxiong",
      "createddate": "2013-10-31 14:55:47.0 EST",
      "updatedby": "fxiong",
      "updateddate": "2013-11-05 19:37:53.767 EST",
      "name": "fiesta-ambiente-1-National",
      "template": "/controller",
      "expiryDate": "2100-11-01 12:00:00.0 EST",
      "indexImage": "1248850583594",
      "indexImageMainUrl": "media/img1.jpg",
      "indexImageThumbnailUrl": "media/img9.png",
      "smobIndexImage": "1248854071385",
      "smobIndexImageMainUrl": "",
      "smobIndexImageThumbnailUrl": "/servlet/Satellite?blobtable=…",
      "heroImage": "1248851233062",
      "heroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "heroImageThumbnailUrl": "",
      "smobHeroImage": "1248854071799",
      "smobHeroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "smobHeroImageThumbnailUrl": "",
      "hotDealUrl": "/hot-deals-test/national/fiesta?sitetype=web ",
      "hotDealSmobUrl": "/smob/hot-deals-test/national/fiesta?sitetype=…"
    },
	{
      "order": 11,
      "id": "1248854804449",
      "uriparameter": "fiesta-ambiente-1",
      "nameplatename": "fiesta",
      "nameplatecks": "17",
      "nameplateId": "1249113492342",
      "derivativeId": "1178856483571",
      "derivativename": "Fiesta Ambiente 1",
      "derivativemarketingname": "Fiesta Ambiente 1",
      "derivativecks": "17353",
      "pricedisclaimer": "Recommended offer … ",
      "blurbs": "Latest Ford Fiesta Ambiente deals from your participating Ford Dealer",
      "features": "Fuel efficient 1…",
      "logo1": "ancap",
      "logo2": "Ecoboost",
      "logo3": "Power",
      "differentiatorlabel1": "ANCAP",
      "differentiatorlabel2": "Ecoboost",
      "differentiatorlabel3": "134 kW power",
      "localdisclaimer": "* Limited offers ...",
      "offerprice": "12000.0",
      "offerregion": "National",
      "campaigns": [
        "campaign3",
        "campaign4"
      ],
      "category": "g",
      "status": "PL",
      "createdby": "fxiong",
      "createddate": "2013-10-31 14:55:47.0 EST",
      "updatedby": "fxiong",
      "updateddate": "2013-11-05 19:37:53.767 EST",
      "name": "fiesta-ambiente-1-National",
      "template": "/controller",
      "expiryDate": "2100-11-01 12:00:00.0 EST",
      "indexImage": "1248850583594",
      "indexImageMainUrl": "media/img1.jpg ",
      "indexImageThumbnailUrl": "media/img9.png",
      "smobIndexImage": "1248854071385",
      "smobIndexImageMainUrl": "media/img1.jpg ",
      "smobIndexImageThumbnailUrl": "/servlet/Satellite?blobtable=…",
      "heroImage": "1248851233062",
      "heroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "heroImageThumbnailUrl": "",
      "smobHeroImage": "1248854071799",
      "smobHeroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "smobHeroImageThumbnailUrl": "",
      "hotDealUrl": "/hot-deals-test/national/fiesta?sitetype=web ",
      "hotDealSmobUrl": "/smob/hot-deals-test/national/fiesta?sitetype=…"
    },
	{
      "order": 8,
      "id": "1248854804450",
      "uriparameter": "fiesta-ambiente-1",
      "nameplatename": "New Fiesta WZ",
      "nameplatecks": "17",
      "nameplateId": "1178856483526",
      "derivativeId": "1178856483571",
      "derivativename": "Fiesta Ambiente 1",
      "derivativemarketingname": "Fiesta Ambiente 1",
      "derivativecks": "17353",
      "pricedisclaimer": "Recommended offer … ",
      "blurbs": "Latest Ford Fiesta Ambiente deals from your participating Ford Dealer",
      "features": "Fuel efficient 1…",
      "logo1": "ancap",
      "logo2": "Ecoboost",
      "logo3": "Power",
      "differentiatorlabel1": "ANCAP",
      "differentiatorlabel2": "Ecoboost",
      "differentiatorlabel3": "134 kW power",
      "localdisclaimer": "* Limited offers ...",
      "offerprice": "30000.0",
      "offerregion": "National",
      "campaigns": [
        "campaign4",
        "campaign2"
      ],
      "category": "g",
      "status": "PL",
      "createdby": "fxiong",
      "createddate": "2013-10-31 14:55:47.0 EST",
      "updatedby": "fxiong",
      "updateddate": "2013-11-05 19:37:53.767 EST",
      "name": "fiesta-ambiente-1-National",
      "template": "/controller",
      "expiryDate": "2100-11-01 12:00:00.0 EST",
      "indexImage": "1248850583594",
      "indexImageMainUrl": "media/img2.jpg ",
      "indexImageThumbnailUrl": "media/img9.png",
      "smobIndexImage": "1248854071385",
      "smobIndexImageMainUrl": "media/img2.jpg ",
      "smobIndexImageThumbnailUrl": "/servlet/Satellite?blobtable=…",
      "heroImage": "1248851233062",
      "heroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "heroImageThumbnailUrl": "",
      "smobHeroImage": "1248854071799",
      "smobHeroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "smobHeroImageThumbnailUrl": "",
      "hotDealUrl": "/hot-deals-test/national/fiesta?sitetype=web ",
      "hotDealSmobUrl": "/smob/hot-deals-test/national/fiesta?sitetype=…"
    },
	{
      "order": 9,
      "id": "1248854804451",
      "uriparameter": "fiesta-ambiente-1",
      "nameplatename": "New Fiesta WZ",
      "nameplatecks": "17",
      "nameplateId": "1178856483527",
      "derivativeId": "1178856483571",
      "derivativename": "Fiesta Ambiente 1",
      "derivativemarketingname": "Fiesta Ambiente 1",
      "derivativecks": "17353",
      "pricedisclaimer": "Recommended offer … ",
      "blurbs": "Latest Ford Fiesta Ambiente deals from your participating Ford Dealer",
      "features": "Fuel efficient 1…",
      "logo1": "ancap",
      "logo2": "Ecoboost",
      "logo3": "Power",
      "differentiatorlabel1": "ANCAP",
      "differentiatorlabel2": "Ecoboost",
      "differentiatorlabel3": "134 kW power",
      "localdisclaimer": "* Limited offers ...",
      "offerprice": "35000.0",
      "offerregion": "National",
      "campaigns": [
        "campaign2",
        "campaign1"
      ],
      "category": "g",
      "status": "PL",
      "createdby": "fxiong",
      "createddate": "2013-10-31 14:55:47.0 EST",
      "updatedby": "fxiong",
      "updateddate": "2013-11-05 19:37:53.767 EST",
      "name": "fiesta-ambiente-1-National",
      "template": "/controller",
      "expiryDate": "2100-11-01 12:00:00.0 EST",
      "indexImage": "1248850583594",
      "indexImageMainUrl": "media/img3.jpg ",
      "indexImageThumbnailUrl": "media/img9.png",
      "smobIndexImage": "1248854071385",
      "smobIndexImageMainUrl": "media/img3.jpg ",
      "smobIndexImageThumbnailUrl": "/servlet/Satellite?blobtable=…",
      "heroImage": "1248851233062",
      "heroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "heroImageThumbnailUrl": "",
      "smobHeroImage": "1248854071799",
      "smobHeroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "smobHeroImageThumbnailUrl": "",
      "hotDealUrl": "/hot-deals-test/national/fiesta?sitetype=web ",
      "hotDealSmobUrl": "/smob/hot-deals-test/national/fiesta?sitetype=…"
    },
	{
      "order": 10,
      "id": "1248854804452",
      "uriparameter": "fiesta-ambiente-1",
      "nameplatename": "New Fiesta WZ",
      "nameplatecks": "17",
      "nameplateId": "1178856483528",
      "derivativeId": "1178856483571",
      "derivativename": "Fiesta Ambiente 1",
      "derivativemarketingname": "Fiesta Ambiente 1",
      "derivativecks": "17353",
      "pricedisclaimer": "Recommended offer … ",
      "blurbs": "Latest Ford Fiesta Ambiente deals from your participating Ford Dealer",
      "features": "Fuel efficient 1…",
      "logo1": "ancap",
      "logo2": "Ecoboost",
      "logo3": "Power",
      "differentiatorlabel1": "ANCAP",
      "differentiatorlabel2": "Ecoboost",
      "differentiatorlabel3": "134 kW power",
      "localdisclaimer": "* Limited offers ...",
      "offerprice": "60000.0",
      "offerregion": "National",
      "campaigns": [
        "campaign4",
        "campaign2"
      ],
      "category": "g",
      "status": "PL",
      "createdby": "fxiong",
      "createddate": "2013-10-31 14:55:47.0 EST",
      "updatedby": "fxiong",
      "updateddate": "2013-11-05 19:37:53.767 EST",
      "name": "fiesta-ambiente-1-National",
      "template": "/controller",
      "expiryDate": "2100-11-01 12:00:00.0 EST",
      "indexImage": "1248850583594",
      "indexImageMainUrl": "media/img4.jpg ",
      "indexImageThumbnailUrl": "media/img9.png",
      "smobIndexImage": "1248854071385",
      "smobIndexImageMainUrl": "media/img4.jpg ",
      "smobIndexImageThumbnailUrl": "/servlet/Satellite?blobtable=…",
      "heroImage": "1248851233062",
      "heroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "heroImageThumbnailUrl": "",
      "smobHeroImage": "1248854071799",
      "smobHeroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "smobHeroImageThumbnailUrl": "",
      "hotDealUrl": "/hot-deals-test/national/fiesta?sitetype=web ",
      "hotDealSmobUrl": "/smob/hot-deals-test/national/fiesta?sitetype=…"
    },
	{
      "order": 6,
      "id": "1248854804453",
      "uriparameter": "fiesta-ambiente-1",
      "nameplatename": "New Fiesta WZ",
      "nameplatecks": "17",
      "nameplateId": "1178856483529",
      "derivativeId": "1178856483571",
      "derivativename": "Fiesta Ambiente 1",
      "derivativemarketingname": "Fiesta Ambiente 1",
      "derivativecks": "17353",
      "pricedisclaimer": "Recommended offer … ",
      "blurbs": "Latest Ford Fiesta Ambiente deals from your participating Ford Dealer",
      "features": "Fuel efficient 1…",
      "logo1": "ancap",
      "logo2": "Ecoboost",
      "logo3": "Power",
      "differentiatorlabel1": "ANCAP",
      "differentiatorlabel2": "Ecoboost",
      "differentiatorlabel3": "134 kW power",
      "localdisclaimer": "* Limited offers ...",
      "offerprice": "55000.0",
      "offerregion": "National",
      "campaigns": [
        "campaign4",
        "campaign1"
      ],
      "category": "g",
      "status": "PL",
      "createdby": "fxiong",
      "createddate": "2013-10-31 14:55:47.0 EST",
      "updatedby": "fxiong",
      "updateddate": "2013-11-05 19:37:53.767 EST",
      "name": "fiesta-ambiente-1-National",
      "template": "/controller",
      "expiryDate": "2100-11-01 12:00:00.0 EST",
      "indexImage": "1248850583594",
      "indexImageMainUrl": "media/img5.jpg ",
      "indexImageThumbnailUrl": "media/img9.png",
      "smobIndexImage": "1248854071385",
      "smobIndexImageMainUrl": "media/img5.jpg ",
      "smobIndexImageThumbnailUrl": "/servlet/Satellite?blobtable=…",
      "heroImage": "1248851233062",
      "heroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "heroImageThumbnailUrl": "",
      "smobHeroImage": "1248854071799",
      "smobHeroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "smobHeroImageThumbnailUrl": "",
      "hotDealUrl": "/hot-deals-test/national/fiesta?sitetype=web ",
      "hotDealSmobUrl": "/smob/hot-deals-test/national/fiesta?sitetype=…"
    },
	{
      "order": 7,
      "id": "1248854804454",
      "uriparameter": "fiesta-ambiente-1",
      "nameplatename": "New Fiesta WZ",
      "nameplatecks": "17",
      "nameplateId": "1178856483530",
      "derivativeId": "1178856483571",
      "derivativename": "Fiesta Ambiente 1",
      "derivativemarketingname": "Fiesta Ambiente 1",
      "derivativecks": "17353",
      "pricedisclaimer": "Recommended offer … ",
      "blurbs": "Latest Ford Fiesta Ambiente deals from your participating Ford Dealer",
      "features": "Fuel efficient 1…",
      "logo1": "ancap",
      "logo2": "Ecoboost",
      "logo3": "Power",
      "differentiatorlabel1": "ANCAP",
      "differentiatorlabel2": "Ecoboost",
      "differentiatorlabel3": "134 kW power",
      "localdisclaimer": "* Limited offers ...",
      "offerprice": "16490.0",
      "offerregion": "National",
      "campaigns": [
        "campaign1",
        "campaign3"
      ],
      "category": "g",
      "status": "PL",
      "createdby": "fxiong",
      "createddate": "2013-10-31 14:55:47.0 EST",
      "updatedby": "fxiong",
      "updateddate": "2013-11-05 19:37:53.767 EST",
      "name": "fiesta-ambiente-1-National",
      "template": "/controller",
      "expiryDate": "2100-11-01 12:00:00.0 EST",
      "indexImage": "1248850583594",
      "indexImageMainUrl": "media/img6.jpg ",
      "indexImageThumbnailUrl": "media/img9.png",
      "smobIndexImage": "1248854071385",
      "smobIndexImageMainUrl": "media/img6.jpg ",
      "smobIndexImageThumbnailUrl": "/servlet/Satellite?blobtable=…",
      "heroImage": "1248851233062",
      "heroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "heroImageThumbnailUrl": "",
      "smobHeroImage": "1248854071799",
      "smobHeroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "smobHeroImageThumbnailUrl": "",
      "hotDealUrl": "/hot-deals-test/national/fiesta?sitetype=web ",
      "hotDealSmobUrl": "/smob/hot-deals-test/national/fiesta?sitetype=…"
    },
	{
      "order": 4,
      "id": "1248854804455",
      "uriparameter": "fiesta-ambiente-1",
      "nameplatename": "New Fiesta WZ",
      "nameplatecks": "17",
      "nameplateId": "1178856483531",
      "derivativeId": "1178856483571",
      "derivativename": "Fiesta Ambiente 1",
      "derivativemarketingname": "Fiesta Ambiente 1",
      "derivativecks": "17353",
      "pricedisclaimer": "Recommended offer … ",
      "blurbs": "Latest Ford Fiesta Ambiente deals from your participating Ford Dealer",
      "features": "Fuel efficient 1…",
      "logo1": "ancap",
      "logo2": "Ecoboost",
      "logo3": "Power",
      "differentiatorlabel1": "ANCAP",
      "differentiatorlabel2": "Ecoboost",
      "differentiatorlabel3": "134 kW power",
      "localdisclaimer": "* Limited offers ...",
      "offerprice": "19000.0",
      "offerregion": "National",
      "campaigns": [
        "campaign1",
        "campaign4"
      ],
      "category": "g",
      "status": "PL",
      "createdby": "fxiong",
      "createddate": "2013-10-31 14:55:47.0 EST",
      "updatedby": "fxiong",
      "updateddate": "2013-11-05 19:37:53.767 EST",
      "name": "fiesta-ambiente-1-National",
      "template": "/controller",
      "expiryDate": "2100-11-01 12:00:00.0 EST",
      "indexImage": "1248850583594",
      "indexImageMainUrl": "media/img1.jpg ",
      "indexImageThumbnailUrl": "media/img9.png",
      "smobIndexImage": "1248854071385",
      "smobIndexImageMainUrl": "media/img1.jpg ",
      "smobIndexImageThumbnailUrl": "/servlet/Satellite?blobtable=…",
      "heroImage": "1248851233062",
      "heroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "heroImageThumbnailUrl": "",
      "smobHeroImage": "1248854071799",
      "smobHeroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "smobHeroImageThumbnailUrl": "",
      "hotDealUrl": "/hot-deals-test/national/fiesta?sitetype=web ",
      "hotDealSmobUrl": "/smob/hot-deals-test/national/fiesta?sitetype=…"
    },
	{
      "order": 5,
      "id": "1248854804456",
      "uriparameter": "fiesta-ambiente-1",
      "nameplatename": "New Fiesta WZ",
      "nameplatecks": "17",
      "nameplateId": "1178856483532",
      "derivativeId": "1178856483571",
      "derivativename": "Fiesta Ambiente 1",
      "derivativemarketingname": "Fiesta Ambiente 1",
      "derivativecks": "17353",
      "pricedisclaimer": "Recommended offer … ",
      "blurbs": "Latest Ford Fiesta Ambiente deals from your participating Ford Dealer",
      "features": "Fuel efficient 1…",
      "logo1": "ancap",
      "logo2": "Ecoboost",
      "logo3": "Power",
      "differentiatorlabel1": "ANCAP",
      "differentiatorlabel2": "Ecoboost",
      "differentiatorlabel3": "134 kW power",
      "localdisclaimer": "* Limited offers ...",
      "offerprice": "23000.0",
      "offerregion": "National",
      "campaigns": [
        "campaign3",
        "campaign4"
      ],
      "category": "g",
      "status": "PL",
      "createdby": "fxiong",
      "createddate": "2013-10-31 14:55:47.0 EST",
      "updatedby": "fxiong",
      "updateddate": "2013-11-05 19:37:53.767 EST",
      "name": "fiesta-ambiente-1-National",
      "template": "/controller",
      "expiryDate": "2100-11-01 12:00:00.0 EST",
      "indexImage": "1248850583594",
      "indexImageMainUrl": "media/img2.jpg ",
      "indexImageThumbnailUrl": "media/img9.png",
      "smobIndexImage": "1248854071385",
      "smobIndexImageMainUrl": "media/img2.jpg ",
      "smobIndexImageThumbnailUrl": "/servlet/Satellite?blobtable=…",
      "heroImage": "1248851233062",
      "heroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "heroImageThumbnailUrl": "",
      "smobHeroImage": "1248854071799",
      "smobHeroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "smobHeroImageThumbnailUrl": "",
      "hotDealUrl": "/hot-deals-test/national/fiesta?sitetype=web ",
      "hotDealSmobUrl": "/smob/hot-deals-test/national/fiesta?sitetype=…"
    },
	{
      "order": 3,
      "id": "1248854804457",
      "uriparameter": "fiesta-ambiente-1",
      "nameplatename": "New Fiesta WZ",
      "nameplatecks": "17",
      "nameplateId": "1178856483533",
      "derivativeId": "1178856483571",
      "derivativename": "Fiesta Ambiente 1",
      "derivativemarketingname": "Fiesta Ambiente 1",
      "derivativecks": "17353",
      "pricedisclaimer": "Recommended offer … ",
      "blurbs": "Latest Ford Fiesta Ambiente deals from your participating Ford Dealer",
      "features": "Fuel efficient 1…",
      "logo1": "ancap",
      "logo2": "Ecoboost",
      "logo3": "Power",
      "differentiatorlabel1": "ANCAP",
      "differentiatorlabel2": "Ecoboost",
      "differentiatorlabel3": "134 kW power",
      "localdisclaimer": "* Limited offers ...",
      "offerprice": "44000.0",
      "offerregion": "National",
      "campaigns": [
        "campaign1",
        "campaign3"
      ],
      "category": "g",
      "status": "PL",
      "createdby": "fxiong",
      "createddate": "2013-10-31 14:55:47.0 EST",
      "updatedby": "fxiong",
      "updateddate": "2013-11-05 19:37:53.767 EST",
      "name": "fiesta-ambiente-1-National",
      "template": "/controller",
      "expiryDate": "2100-11-01 12:00:00.0 EST",
      "indexImage": "1248850583594",
      "indexImageMainUrl": "media/img3.jpg ",
      "indexImageThumbnailUrl": "media/img9.png",
      "smobIndexImage": "1248854071385",
      "smobIndexImageMainUrl": "media/img3.jpg ",
      "smobIndexImageThumbnailUrl": "/servlet/Satellite?blobtable=…",
      "heroImage": "1248851233062",
      "heroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "heroImageThumbnailUrl": "",
      "smobHeroImage": "1248854071799",
      "smobHeroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "smobHeroImageThumbnailUrl": "",
      "hotDealUrl": "/hot-deals-test/national/fiesta?sitetype=web ",
      "hotDealSmobUrl": "/smob/hot-deals-test/national/fiesta?sitetype=…"
    },
	{
      "order": 2,
      "id": "1248854804458",
      "uriparameter": "fiesta-ambiente-1",
      "nameplatename": "New Fiesta WZ",
      "nameplatecks": "17",
      "nameplateId": "1178856483524",
      "derivativeId": "1178856483571",
      "derivativename": "Fiesta Ambiente 1",
      "derivativemarketingname": "Fiesta Ambiente 1",
      "derivativecks": "17353",
      "pricedisclaimer": "Recommended offer … ",
      "blurbs": "Latest Ford Fiesta Ambiente deals from your participating Ford Dealer",
      "features": "Fuel efficient 1…",
      "logo1": "ancap",
      "logo2": "Ecoboost",
      "logo3": "Power",
      "differentiatorlabel1": "ANCAP",
      "differentiatorlabel2": "Ecoboost",
      "differentiatorlabel3": "134 kW power",
      "localdisclaimer": "* Limited offers ...",
      "offerprice": "28000.0",
      "offerregion": "National",
      "campaigns": [
        "campaign3",
        "campaign4"
      ],
      "category": "g",
      "status": "PL",
      "createdby": "fxiong",
      "createddate": "2013-10-31 14:55:47.0 EST",
      "updatedby": "fxiong",
      "updateddate": "2013-11-05 19:37:53.767 EST",
      "name": "fiesta-ambiente-1-National",
      "template": "/controller",
      "expiryDate": "2100-11-01 12:00:00.0 EST",
      "indexImage": "1248850583594",
      "indexImageMainUrl": "media/img4.jpg ",
      "indexImageThumbnailUrl": "media/img9.png",
      "smobIndexImage": "1248854071385",
      "smobIndexImageMainUrl": "media/img4.jpg ",
      "smobIndexImageThumbnailUrl": "/servlet/Satellite?blobtable=…",
      "heroImage": "1248851233062",
      "heroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "heroImageThumbnailUrl": "",
      "smobHeroImage": "1248854071799",
      "smobHeroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "smobHeroImageThumbnailUrl": "",
      "hotDealUrl": "/hot-deals-test/national/fiesta?sitetype=web ",
      "hotDealSmobUrl": "/smob/hot-deals-test/national/fiesta?sitetype=…"
    },
	{
      "order": 13,
      "id": "1248854804459",
      "uriparameter": "fiesta-ambiente-1",
      "nameplatename": "New Fiesta WZ",
      "nameplatecks": "17",
      "nameplateId": "1178856483525",
      "derivativeId": "1178856483571",
      "derivativename": "Fiesta Ambiente 1",
      "derivativemarketingname": "Fiesta Ambiente 1",
      "derivativecks": "17353",
      "pricedisclaimer": "Recommended offer … ",
      "blurbs": "Latest Ford Fiesta Ambiente deals from your participating Ford Dealer",
      "features": "Fuel efficient 1…",
      "logo1": "ancap",
      "logo2": "Ecoboost",
      "logo3": "Power",
      "differentiatorlabel1": "ANCAP",
      "differentiatorlabel2": "Ecoboost",
      "differentiatorlabel3": "134 kW power",
      "localdisclaimer": "* Limited offers ...",
      "offerprice": "17490.0",
      "offerregion": "National",
      "campaigns": [
        "campaign2"
      ],
      "category": "g",
      "status": "PL",
      "createdby": "fxiong",
      "createddate": "2013-10-31 14:55:47.0 EST",
      "updatedby": "fxiong",
      "updateddate": "2013-11-05 19:37:53.767 EST",
      "name": "fiesta-ambiente-1-National",
      "template": "/controller",
      "expiryDate": "2100-11-01 12:00:00.0 EST",
      "indexImage": "1248850583594",
      "indexImageMainUrl": "media/img5.jpg ",
      "indexImageThumbnailUrl": "media/img9.png",
      "smobIndexImage": "1248854071385",
      "smobIndexImageMainUrl": "media/img5.jpg ",
      "smobIndexImageThumbnailUrl": "/servlet/Satellite?blobtable=…",
      "heroImage": "1248851233062",
      "heroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "heroImageThumbnailUrl": "",
      "smobHeroImage": "1248854071799",
      "smobHeroImageMainUrl": "/servlet/Satellite?blobtable=…",
      "smobHeroImageThumbnailUrl": "",
      "hotDealUrl": "/hot-deals-test/national/fiesta?sitetype=web ",
      "hotDealSmobUrl": "/smob/hot-deals-test/national/fiesta?sitetype=…"
    }
  ],
  "campaigns": [
    "campaign1",
    "campaign2",
    "campaign3",
    "campaign4"
  ]
}